"""
Step-by-step walkthrough of b2b_revenue_forecasting (v0.3+).

Demonstrates every public capability end-to-end on the synthetic demo
dataset generated by examples/generate_demo_data.py:

  Step 1.  Load the CSV
  Step 2.  Build the hierarchy (with the brand-new IC column from CSV)
  Step 3.  Declare metrics + their direction (user input)
  Step 4.  Suggest weights from data (correlation magnitude)
  Step 5.  Override a suggested weight where domain disagrees
  Step 6.  Inspect the normalized-weights view (what stakeholders see)
  Step 7.  Sanity-check via exploratory direction inference
  Step 8.  Cascade quota with multi-metric blend + per-region hedge
  Step 9.  Add a CRO override + show how the carve-out interacts
  Step 10. Diagnose pipeline health (multi-column pipeline)
  Step 11. Redistribute IC quotas based on pipeline coverage
  Step 12. Reconcile manager commits with historical bias quotients
  Step 13. Export all outputs to CSV (with hedge audit columns)
  Step 14. Write outputs to a SQL database (SQLite example)
  Step 15. Generate an interactive HTML dashboard
  ── PART B: White-space planning (forward-looking cascade + gates) ──
  Step 16. Cascade with FORWARD-looking metrics + a hard gate
  Step 17. Reconcile using HISTORICAL attainment (instead of pipeline)
  Step 18. Summary report

Run from project root:
    python examples/walkthrough.py
"""
import warnings
import pandas as pd
import sys
sys.path.insert(0, '.')

from b2b_revenue_forecasting import (
    SalesHierarchy,
    QuotaCascader,
    PipelineAdjuster,
    CommitReconciler,
    MetricSpec,
)

# Pretty separators for the printed walkthrough
H1 = '=' * 90
H2 = '-' * 90


def section(n, title):
    print(f"\n\n{H1}\nSTEP {n}: {title}\n{H1}")


def sub(text):
    print(f"\n{H2}\n{text}\n{H2}")


# ======================================================================
# STEP 1 — Load the CSV
# ======================================================================
section(1, "Load the analyst-uploaded CSV")
df = pd.read_csv('examples/data/demo_hierarchy.csv', keep_default_na=False)
print(f"Loaded {len(df)} IC rows from examples/data/demo_hierarchy.csv")
print(f"Columns ({len(df.columns)}): {list(df.columns)}")
print(f"\nFirst 2 rows (key columns only):")
print(df[['Region', 'IC', 'Q4_NetNewACV', 'Q4_CloudSeats',
         'LTM_ExpansionSpent', 'Q4_Has_Active_Cert',
         'Open_Pipeline', 'Is_Brand_New']].head(2).to_string(index=False))


# ======================================================================
# STEP 2 — Build the hierarchy with the brand-new column
# ======================================================================
section(2, "Build the SalesHierarchy (brand-new flag ingested from CSV)")
taxonomy = ['Global', 'Region', 'RVP', 'Director', 'Manager', 'IC']
metrics_cols = [
    'Q1_NetNewACV', 'Q2_NetNewACV', 'Q3_NetNewACV', 'Q4_NetNewACV',
    'Q1_CloudSeats', 'Q2_CloudSeats', 'Q3_CloudSeats', 'Q4_CloudSeats',
    'Q1_DCSeats', 'Q2_DCSeats', 'Q3_DCSeats', 'Q4_DCSeats',
    'LTM_ExpansionSpent',
    'Q1_Has_Active_Cert', 'Q2_Has_Active_Cert',
    'Q3_Has_Active_Cert', 'Q4_Has_Active_Cert',
    'Open_Pipeline', 'Late_Stage_Commit', 'Best_Case_Adds',
]

hierarchy = SalesHierarchy()
hierarchy.from_dataframe(
    df,
    path_cols=taxonomy,
    metrics_cols=metrics_cols,
    brand_new_col='Is_Brand_New',   # ingest the brand-new flag from CSV
)
print(f"Total nodes in DAG: {len(hierarchy.graph.nodes)}")
print(f"Individual Contributors (leaves): {len(hierarchy.get_leaves('Global_Corp'))}")
print(f"Regions:  {list(hierarchy.get_children('Global_Corp'))}")

# Show that the brand-new flag landed on the right ICs
flagged = [n for n in hierarchy.graph.nodes
           if hierarchy.graph.nodes[n].get('_is_brand_new')]
print(f"\nICs flagged brand-new via CSV: {len(flagged)}")
print(f"Examples: {flagged[:3]}")


# ======================================================================
# STEP 3 — Declare metrics with USER-PROVIDED direction
# ======================================================================
section(3, "Declare which metrics drive cascading + their direction")
print("Direction is a DOMAIN decision: the analyst tells the package whether")
print("more-of-X means MORE quota (proportional) or LESS quota (inverse).")
print("The package never overrides this from data.\n")

declared_metrics = [
    MetricSpec('NetNewACV',       direction='proportional', weight=1.0, lookback=4),
    MetricSpec('CloudSeats',      direction='proportional', weight=1.0, lookback=4),
    MetricSpec('DCSeats',         direction='inverse',      weight=1.0, lookback=4),
    MetricSpec('ExpansionSpent',  direction='inverse',      weight=1.0,
               columns=['LTM_ExpansionSpent']),
    MetricSpec('Has_Active_Cert', direction='proportional', weight=1.0, lookback=4),
]
for m in declared_metrics:
    print(f"  {m.name:<18s} direction={m.direction:<13s} "
          f"lookback={m.lookback}  columns={m.resolved_columns()}")


# ======================================================================
# STEP 4 — Suggest weights via correlation (directions stay user's)
# ======================================================================
section(4, "Suggest weights from data (correlation magnitude)")
print("Pass the declared MetricSpecs to suggest_weights. Each metric is")
print("correlated against NetNewACV_4Q_sum; |correlation| becomes the")
print("suggested weight. Directions are preserved exactly as declared.\n")

# Aggregate the per-quarter boolean cert columns into a single 4Q sum
# (range 0..4 per IC) so it correlates cleanly against the dollar target.
df['Has_Cert_4Q_sum'] = (
    df[['Q1_Has_Active_Cert', 'Q2_Has_Active_Cert',
        'Q3_Has_Active_Cert', 'Q4_Has_Active_Cert']]
    .astype(int).sum(axis=1)
)

# Direction is REQUIRED on every candidate. All 4 secondary metrics go
# through the suggester so each weight is grounded in the data.
# (NetNewACV is the cascade target itself — correlating it with itself
# would always give 1.0, so we pin it manually as the anchor.)
candidates = [
    {'name': 'CloudSeats',      'column': 'CloudSeats_4Q_sum',
     'direction': 'proportional', 'lookback': 4},
    {'name': 'DCSeats',         'column': 'DCSeats_4Q_sum',
     'direction': 'inverse',      'lookback': 4},
    {'name': 'ExpansionSpent',  'column': 'LTM_ExpansionSpent',
     'columns': ['LTM_ExpansionSpent'],
     'direction': 'inverse',      'lookback': 1},
    {'name': 'Has_Active_Cert', 'column': 'Has_Cert_4Q_sum',
     'direction': 'proportional', 'lookback': 4},
]

with warnings.catch_warnings(record=True) as warning_log:
    warnings.simplefilter('always')
    suggested, report = MetricSpec.suggest_weights(
        df,
        target_column='NetNewACV_4Q_sum',
        candidate_metrics=candidates,
    )

print("Suggested weights:")
for s in suggested:
    r = report[s.name]
    match_str = ('agrees' if r['direction_matches_data']
                 else 'DISAGREES — but user direction kept')
    print(f"  {s.name:<18s} direction={s.direction:<13s} "
          f"weight={s.weight:.3f}  corr={r['correlation']:+.3f}  ({match_str})")

if warning_log:
    print("\nWarnings emitted by suggest_weights:")
    for w in warning_log:
        print(f"  - {w.message}")
else:
    print("\nNo direction-mismatch warnings fired — data agrees with all directions.")


# ======================================================================
# STEP 5 — Override a suggested weight where domain knowledge disagrees
# ======================================================================
section(5, "Override a suggested weight (Pattern A: mutate after suggestion)")
print("Suppose DCSeats came back weak (0.067) but the RevOps team believes")
print("it's a more important headwind than the data shows for next quarter")
print("(maybe a known platform sunset). The analyst overrides just that")
print("weight — the rest stay data-driven.\n")

# Edit in place — suggested is a list of MetricSpec, fully mutable
for s in suggested:
    if s.name == 'DCSeats':
        before = s.weight
        s.weight = 0.4   # analyst's domain judgment
        print(f"  DCSeats weight: {before:.3f} (suggested) -> {s.weight:.3f} (overridden)")

# Pin the cascade target (NetNewACV) at the anchor weight of 1.0
cascade_metrics = [
    MetricSpec('NetNewACV', direction='proportional', weight=1.0, lookback=4),
    *suggested,
]

print("\nFinal cascade metric set:")
for m in cascade_metrics:
    print(f"  {m.name:<18s} direction={m.direction:<13s} weight={m.weight:.3f}")


# ======================================================================
# STEP 6 — Inspect the normalized-weights view
# ======================================================================
section(6, "Normalized-weights view (what stakeholders should actually see)")
print("Input weights don't sum to 1 — the package normalizes them at")
print("cascade time across the ACTIVE metrics (weight > 0). This is the")
print("table to show stakeholders: it answers 'how much does each signal")
print("actually pull the allocation?'\n")

print(MetricSpec.format_normalized_weights(cascade_metrics))

# Same data is also available as a DataFrame for further analysis
weights_df = MetricSpec.normalized_weights(cascade_metrics)
print(f"\nAvailable programmatically as a DataFrame:")
print(weights_df.to_string(index=False))


# ======================================================================
# STEP 7 — Sanity-check via exploratory direction inference
# ======================================================================
section(7, "Sanity-check: infer BOTH direction and weight from data")
print("This is a tool for exploration ONLY — it lets you confirm your")
print("domain-driven directions agree with the data sign.\n")
explored, exp_report = MetricSpec.suggest_directions_and_weights(
    df,
    target_column='NetNewACV_4Q_sum',
    candidate_metrics=candidates,
)
print("Data-inferred directions:")
for s in explored:
    r = exp_report[s.name]
    print(f"  {s.name:<18s} inferred={s.direction:<13s} "
          f"weight={s.weight:.3f}  (corr={r['correlation']:+.3f})")


# ======================================================================
# STEP 8 — Cascade with multi-metric blend + per-region hedge
# ======================================================================
section(8, "Cascade $50M with multi-metric blend + per-region hedge")
print("Hedge: NA aggressive 10%, EMEA + APAC standard 5%, Global 5%.")
print("Brand-new ICs are picked up automatically from the CSV column.\n")

cascader = QuotaCascader(hierarchy)
MACRO_TARGET = 50_000_000.0

per_node_hedge = {
    'Global_Corp': 1.05,
    'NA':   1.10,
    'EMEA': 1.05,
    'APAC': 1.05,
}

quotas = cascader.cascade_quota(
    'Global_Corp',
    MACRO_TARGET,
    hedge_multiplier=per_node_hedge,
    metrics=cascade_metrics,
    new_ic_attr='_is_brand_new',   # read flag from CSV-ingested attribute
)
# The normalized-weights table is auto-printed at the top of every
# multi-metric cascade. Same DataFrame is also accessible afterward:
#   cascader.weights_report  -> pd.DataFrame

leaves = hierarchy.get_leaves('Global_Corp')
ic_total = sum(quotas[ic] for ic in leaves)
print(f"Macro target:                ${MACRO_TARGET:>15,.2f}")
print(f"Sum of all IC quotas:        ${ic_total:>15,.2f}")
print(f"Compounded overassignment:   {(ic_total/MACRO_TARGET - 1)*100:>14.2f}%")
print(f"Number of ICs:               {len(leaves):>15d}")

print(f"\nPer-region totals at the RVP layer:")
for region in ['NA', 'EMEA', 'APAC']:
    region_total = quotas.get(region, 0.0)
    print(f"  {region:<6s} cascaded quota: ${region_total:,.2f}")

print(f"\nSample IC quotas (3 veteran + 3 brand-new):")
veterans = [n for n in leaves if not hierarchy.graph.nodes[n].get('_is_brand_new')][:3]
brand_new = [n for n in leaves if hierarchy.graph.nodes[n].get('_is_brand_new')][:3]
for ic in veterans + brand_new:
    flag = ' (BRAND-NEW)' if hierarchy.graph.nodes[ic].get('_is_brand_new') else ''
    print(f"  {ic:<55s} ${quotas[ic]:>12,.2f}{flag}")


# ======================================================================
# STEP 9 — CRO override on a strategic hire
# ======================================================================
section(9, "Re-cascade with CRO override for a strategic hire")
print("CRO mandates IC_Mgr_Dir_RVP_NA_1_1_1_1 must carry exactly $1.2M")
print("regardless of what the algorithm would assign.\n")

strategic_ic = veterans[0]   # pick a real IC id for the demo
override = {strategic_ic: 1_200_000.0}
quotas_with_override = cascader.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=per_node_hedge,
    metrics=cascade_metrics,
    new_ic_attr='_is_brand_new',
    new_ic_overrides=override,
)
print(f"  {strategic_ic} algorithmic quota:   ${quotas[strategic_ic]:>12,.2f}")
print(f"  {strategic_ic} CRO-locked quota:    ${quotas_with_override[strategic_ic]:>12,.2f}")
print(f"  Manager total still preserved? Sum of that manager's ICs = "
      f"${sum(quotas_with_override[c] for c in hierarchy.get_children(list(hierarchy.graph.predecessors(strategic_ic))[0])):,.2f}")


# ======================================================================
# STEP 10 — Diagnose pipeline health (multi-column pipeline)
# ======================================================================
section(10, "Diagnose pipeline coverage (sums 3 pipeline columns per IC)")
print("Pipeline = Open_Pipeline + Late_Stage_Commit + Best_Case_Adds.")
print("Per-region risk thresholds — NA aggressive, APAC conservative.\n")

adjuster = PipelineAdjuster(
    hierarchy,
    quotas,
    pipeline_attr=['Open_Pipeline', 'Late_Stage_Commit', 'Best_Case_Adds'],
)

coverage_thresholds = {
    'NA':       {'healthy': 1.5, 'at_risk': 0.8},
    'EMEA':     {'healthy': 2.5, 'at_risk': 1.2},
    'APAC':     {'healthy': 3.0, 'at_risk': 1.5},
    '_default': {'healthy': 2.0, 'at_risk': 1.0},
}
diagnosis = adjuster.diagnose(coverage_thresholds)

# Summary by risk status across the whole org
risk_summary = diagnosis.groupby('Risk_Status').agg(
    Nodes=('Node', 'count'),
    Total_Quota=('Cascaded_Quota', 'sum'),
    Total_Pipeline=('Pipeline', 'sum'),
).sort_values('Nodes', ascending=False).reset_index()

print("Risk-status summary across ALL hierarchy nodes:")
print(risk_summary.to_string(index=False,
                              formatters={'Total_Quota': '${:,.0f}'.format,
                                          'Total_Pipeline': '${:,.0f}'.format}))

# Drill into IC-level rows for a single manager
sample_mgr = list({list(hierarchy.graph.predecessors(ic))[0]
                   for ic in veterans})[0]
mgr_ics = hierarchy.get_children(sample_mgr)
print(f"\nIC-level coverage under {sample_mgr}:")
print(diagnosis[diagnosis['Node'].isin(mgr_ics)]
      [['Node', 'Cascaded_Quota', 'Pipeline', 'Coverage_Ratio', 'Risk_Status']]
      .to_string(index=False,
                 formatters={'Cascaded_Quota': '${:,.0f}'.format,
                             'Pipeline': '${:,.0f}'.format,
                             'Coverage_Ratio': '{:.2f}x'.format}))


# ======================================================================
# STEP 11 — Redistribute IC quotas based on pipeline coverage
# ======================================================================
section(11, "Redistribute IC quotas based on pipeline health (zero-sum)")
print("Within each manager: ICs with low pipeline coverage shed quota to")
print("ICs with high coverage, capped at ±20% per IC. Manager totals are")
print("preserved exactly.\n")

# Lock the strategic hire so they aren't touched by redistribution
adjusted = adjuster.adjust(
    mode='redistribute',
    coverage_thresholds=coverage_thresholds,
    max_adjustment_pct=0.20,
    locked_nodes={strategic_ic},
)

# Count adjustments
adjusted_count = sum(1 for ic in leaves
                     if abs(adjusted.get(ic, 0) - quotas.get(ic, 0)) > 0.01)
print(f"ICs whose quota was adjusted: {adjusted_count} of {len(leaves)}")

# Verify zero-sum per manager
manager_nodes = [n for n in hierarchy.graph.nodes
                 if list(hierarchy.graph.successors(n))
                 and all(hierarchy.graph.out_degree(c) == 0
                         for c in hierarchy.graph.successors(n))]
biggest_delta_mgr = max(manager_nodes, key=lambda m: abs(
    sum(adjusted[ic] - quotas[ic] for ic in hierarchy.get_children(m))
))
delta = sum(adjusted[ic] - quotas[ic]
            for ic in hierarchy.get_children(biggest_delta_mgr))
print(f"Largest manager-level drift (should be ~$0): "
      f"${delta:,.2f} at {biggest_delta_mgr}")

# Show a few movers
movers = sorted(
    [(ic, quotas[ic], adjusted[ic], adjusted[ic] - quotas[ic]) for ic in leaves
     if abs(adjusted[ic] - quotas[ic]) > 0.01],
    key=lambda t: abs(t[3]),
    reverse=True,
)[:5]
print(f"\nTop 5 ICs by absolute redistribution:")
print(f"  {'IC':<50s} {'Original':>14s} {'Adjusted':>14s} {'Delta':>12s}")
for ic, orig, adj, d in movers:
    print(f"  {ic:<50s} ${orig:>12,.0f} ${adj:>12,.0f} {'+'if d>=0 else ''}${d:>10,.0f}")


# ======================================================================
# STEP 12 — Reconcile manager commits with historical bias
# ======================================================================
section(12, "Reconcile manager commits with historical bias quotients")
print("Each manager's history is read; their commit is auto-adjusted by")
print("their historical 'sandbagger / happy-ears' ratio.\n")

commit_history = pd.read_csv('examples/data/demo_commit_history.csv')
reconciler = CommitReconciler(commit_history)

print("Historical bias quotients:")
for mgr_id, bias in reconciler.bias_weights.items():
    label = ('sandbagger' if bias > 1.1 else
             'happy ears' if bias < 0.9 else 'truth-teller')
    print(f"  {mgr_id:<35s} bias = {bias:.2f}  ({label})")

print("\nReconciling Q1 commits ($300K per manager) with ML baseline of $320K:")
current_commit = 300_000.0
ml_forecast = 320_000.0
for mgr_id in reconciler.bias_weights:
    raw_adj = current_commit * reconciler.bias_weights[mgr_id]
    blended = reconciler.reconcile_forecast(mgr_id, current_commit, ml_forecast)
    print(f"  {mgr_id}")
    print(f"     Manager committed:     ${current_commit:,.0f}")
    print(f"     Bias-adjusted human:   ${raw_adj:,.0f}")
    print(f"     Blended with ML:       ${blended:,.0f}")


# ======================================================================
# STEP 13 — Export every output to CSV
# ======================================================================
import os
section(13, "Export all outputs to CSV (with hedge audit columns)")
print("Run the cascade TWICE: once with the per-region hedge, once with")
print("hedge=1.0 (no overassignment anywhere). The CSV gets both columns")
print("plus the dollar buffer and overassignment percentage per node.\n")

OUT_DIR = 'examples/data'
os.makedirs(OUT_DIR, exist_ok=True)

# Second cascade: same inputs, NO hedging anywhere (audit baseline)
quotas_unhedged = cascader.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=1.0,           # no hedge => exact $50M at root
    metrics=cascade_metrics,
    new_ic_attr='_is_brand_new',
    verbose=False,
)

# 1) Cascaded quotas — every node at every level, both with and without hedge
cascaded_df = cascader.quotas_to_dataframe(
    quotas, level_names=taxonomy,
    unhedged_quotas=quotas_unhedged,    # adds 3 audit columns
)
cascaded_path = os.path.join(OUT_DIR, 'output_cascaded_quotas.csv')
cascaded_df.to_csv(cascaded_path, index=False)
print(f"[1/5] {cascaded_path}")
print(f"      rows: {len(cascaded_df)} (every node at every level)")
print(f"      columns: {list(cascaded_df.columns)}")
print(cascaded_df.head(8).to_string(index=False))

# 2) Normalized weights — what stakeholders see
weights_path = os.path.join(OUT_DIR, 'output_normalized_weights.csv')
cascader.weights_report.to_csv(weights_path, index=False)
print(f"\n[2/5] {weights_path}")
print(cascader.weights_report.to_string(index=False))

# 3) Pipeline diagnosis — coverage + risk status for every node
diagnosis_path = os.path.join(OUT_DIR, 'output_pipeline_diagnosis.csv')
diagnosis.to_csv(diagnosis_path, index=False)
print(f"\n[3/5] {diagnosis_path}")
print(f"      rows: {len(diagnosis)} (every node)")
print(diagnosis.head(5).to_string(index=False))

# 4) Redistributed quotas — original vs adjusted with deltas (IC level only)
redist_df = cascader.quotas_diff_to_dataframe(
    original=quotas, adjusted=adjusted, level_names=taxonomy,
)
redist_path = os.path.join(OUT_DIR, 'output_redistributed_quotas.csv')
redist_df.to_csv(redist_path, index=False)
print(f"\n[4/5] {redist_path}")
print(f"      rows: {len(redist_df)} (IC level)")
# Show the top 5 movers
top_movers = redist_df.reindex(
    redist_df['delta'].abs().sort_values(ascending=False).index
).head(5)
print(top_movers.to_string(index=False))

# 5) Commit reconciliation — bias quotients + blended forecasts
commits_input = pd.DataFrame({
    'Manager_ID': list(reconciler.bias_weights.keys()),
    'Current_Commit': [300_000.0] * len(reconciler.bias_weights),
    'Machine_Forecast': [320_000.0] * len(reconciler.bias_weights),
})
recon_df = reconciler.reconcile_all(
    commits_input,
    manager_col='Manager_ID',
    commit_col='Current_Commit',
    machine_col='Machine_Forecast',
)
recon_path = os.path.join(OUT_DIR, 'output_commit_reconciliation.csv')
recon_df.to_csv(recon_path, index=False)
print(f"\n[5/5] {recon_path}")
print(recon_df.to_string(index=False))


# ======================================================================
# STEP 14 — Write outputs to a SQL database (SQLite example)
# ======================================================================
import sqlite3
section(14, "Write outputs to a SQL database (SQLite example)")
print("Every output is already a DataFrame, so pandas' built-in to_sql()")
print("handles writes to ANY SQLAlchemy-compatible database (SQLite,")
print("Postgres, MySQL, Snowflake, BigQuery, Redshift, etc). Here we")
print("demo with SQLite — same pattern works for production DBs.\n")

# Pick a writable location for the SQLite DB. On most local filesystems
# OUT_DIR works fine; some sandboxes / network mounts don't support
# SQLite's file-locking, so fall back to the system tempdir.
import tempfile
preferred_db_path = os.path.join(OUT_DIR, 'cascade_results.db')
fallback_db_path = os.path.join(tempfile.gettempdir(), 'cascade_results.db')

def _try_write_sqlite(target_path):
    if os.path.exists(target_path):
        os.remove(target_path)
    tables = {
        'cascaded_quotas':       cascaded_df,
        'normalized_weights':    cascader.weights_report,
        'pipeline_diagnosis':    diagnosis,
        'redistributed_quotas':  redist_df,
        'commit_reconciliation': recon_df,
    }
    with sqlite3.connect(target_path) as conn:
        for name, frame in tables.items():
            frame.to_sql(name, conn, if_exists='replace', index=False)
            n = conn.execute(f'SELECT COUNT(*) FROM {name}').fetchone()[0]
            print(f"  wrote {n:>4d} rows to table `{name}`")
    return target_path

try:
    db_path = _try_write_sqlite(preferred_db_path)
    print(f"\nDatabase: {db_path}")
except (sqlite3.OperationalError, OSError, PermissionError) as e:
    print(f"  ({preferred_db_path} not writable: {e}; falling back to tempdir)")
    db_path = _try_write_sqlite(fallback_db_path)
    print(f"\nDatabase: {db_path}  (fallback location)")

# Smoke-test: read one row back to prove it's queryable
print(f"\nSmoke-test query — region totals from cascaded_quotas:")
with sqlite3.connect(db_path) as conn:
    rows = conn.execute(
        "SELECT level, node_id, cascaded_quota, unhedged_quota "
        "FROM cascaded_quotas WHERE depth = 1 ORDER BY cascaded_quota DESC"
    ).fetchall()
    for level, node, cascaded, unhedged in rows:
        print(f"  {level:<8s} {node:<6s} cascaded ${cascaded:>14,.2f}  "
              f"unhedged ${unhedged:>14,.2f}")

print(f"\nFor Postgres / Snowflake / etc, swap the sqlite3 connection for a")
print(f"SQLAlchemy engine and the same to_sql() calls work unchanged:")
print(f"  from sqlalchemy import create_engine")
print(f"  engine = create_engine('postgresql://user:pass@host/db')")
print(f"  cascaded_df.to_sql('cascaded_quotas', engine, if_exists='replace')")


# ======================================================================
# STEP 15 — Generate an interactive HTML dashboard
# ======================================================================
section(15, "Generate an interactive HTML dashboard")
print("Self-contained HTML file with Chart.js visualizations. Opens in")
print("any browser, shareable via email or intranet upload, no server")
print("required. Embeds all data inline as JSON.\n")

dashboard_path = os.path.join(OUT_DIR, 'cascade_dashboard.html')
cascader.to_html_dashboard(
    quotas,
    output_path=dashboard_path,
    title="Q1 Cascade Dashboard — $50M Multi-Metric Plan",
    macro_target=MACRO_TARGET,
    unhedged_quotas=quotas_unhedged,    # adds hedge-buffer comparison
    adjusted_quotas=adjusted,           # adds redistribution chart
    diagnosis=diagnosis,                # adds risk-status chart
)
print(f"Wrote dashboard: {dashboard_path}")
print(f"  size: {os.path.getsize(dashboard_path):,} bytes")
print(f"  charts: Region totals · Top 20 ICs · Top redistributions · Risk status")
print(f"  Open in any browser: file://{os.path.abspath(dashboard_path)}")


# ======================================================================
# ===== PART B — WHITE-SPACE PLANNING (alternative philosophy) =========
# ======================================================================
# Up to Step 15 we used "earned planning" — historical signals drive the
# cascade, current pipeline drives reconciliation. Some orgs flip this:
# they plan around FORWARD-looking opportunity ("what can be achieved")
# and reconcile against HISTORICAL signals ("how have they actually
# performed against past targets"). Steps 16–17 show that flow on the
# same dataset, using NEW columns the analyst added to the same CSV.

# ======================================================================
# STEP 16 — Forward-looking cascade with a hard gate
# ======================================================================
section(16, "Cascade with FORWARD-looking metrics + a hard gate")
print("Forward-looking metrics: current installed seats (proportional),")
print("knowledge workers per territory (proportional), LTM expansion")
print("spend (inverse — high spend dampens upside). Gate: unmigrated")
print("seats == 0 means '$0 migration quota' — no white space, no target.\n")

# Build a fresh hierarchy that ALSO ingests the new forward columns
white_space_metrics_cols = metrics_cols + [
    'Current_Seats_ProductX', 'Knowledge_Workers_Count', 'Unmigrated_Seats',
]
hierarchy_ws = SalesHierarchy()
hierarchy_ws.from_dataframe(
    df, path_cols=taxonomy, metrics_cols=white_space_metrics_cols,
    brand_new_col='Is_Brand_New',
)
cascader_ws = QuotaCascader(hierarchy_ws)

# Forward-looking metric slate (no historical attainment here)
forward_metrics = [
    MetricSpec('Current_Seats_ProductX',  direction='proportional',
               weight=1.0, columns=['Current_Seats_ProductX']),
    MetricSpec('Knowledge_Workers_Count', direction='proportional',
               weight=0.7, columns=['Knowledge_Workers_Count']),
    MetricSpec('LTM_ExpansionSpent',      direction='inverse',
               weight=0.5, columns=['LTM_ExpansionSpent']),  # dampener
]
# Gate: territories with zero unmigrated seats must get $0
gate_metrics = [
    MetricSpec('Unmigrated_Seats', columns=['Unmigrated_Seats']),
]

ws_quotas = cascader_ws.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=1.05,
    metrics=forward_metrics,
    gate_metrics=gate_metrics,
    new_ic_attr='_is_brand_new',
)

ws_leaves = hierarchy_ws.get_leaves('Global_Corp')
ws_ic_total = sum(ws_quotas[ic] for ic in ws_leaves)
ws_gated_leaves = [ic for ic in ws_leaves if ic in cascader_ws.gated_nodes]
ws_zero_leaves = [ic for ic in ws_leaves if ws_quotas[ic] == 0]

print(f"\nWhite-space cascade summary:")
print(f"  Macro target:        ${MACRO_TARGET:>12,.2f}")
print(f"  Sum of IC quotas:    ${ws_ic_total:>12,.2f}")
print(f"  Gated IC nodes:      {len(ws_gated_leaves):>4d}  (got $0 — no white space)")
print(f"  Non-gated $0 ICs:    {len(ws_zero_leaves) - len(ws_gated_leaves):>4d}")
print(f"  Funded IC nodes:     {len([ic for ic in ws_leaves if ws_quotas[ic] > 0]):>4d}")

# Show that the whole APAC subtree under Mgr_Dir_RVP_APAC_1_1_1 is gated
mgr_with_zero_team = 'Mgr_Dir_RVP_APAC_1_1_1'
if mgr_with_zero_team in cascader_ws.gated_nodes:
    mgr_team_ics = hierarchy_ws.get_children(mgr_with_zero_team)
    print(f"\n  Whole-subtree gate propagation example:")
    print(f"    {mgr_with_zero_team} (entire team fully migrated): "
          f"${ws_quotas.get(mgr_with_zero_team, 0):,.2f}")
    for ic in mgr_team_ics[:3]:
        print(f"      └─ {ic}: ${ws_quotas[ic]:,.2f}")
    print(f"      ({len(mgr_team_ics)} ICs total — all $0)")

# Export the cascaded quotas CSV with the is_gated column
ws_cascaded_df = cascader_ws.quotas_to_dataframe(ws_quotas, level_names=taxonomy)
ws_csv_path = os.path.join(OUT_DIR, 'output_whitespace_cascaded_quotas.csv')
ws_cascaded_df.to_csv(ws_csv_path, index=False)
print(f"\nWrote {ws_csv_path}")
print(f"  columns: {list(ws_cascaded_df.columns)}")
print(f"  Sample gated IC rows (is_gated=True, cascaded_quota=0):")
print(ws_cascaded_df[ws_cascaded_df['is_gated'] & ws_cascaded_df['is_leaf']]
      .head(3).to_string(index=False))


# ======================================================================
# STEP 17 — Reconcile using HISTORICAL attainment (no current pipeline)
# ======================================================================
section(17, "Reconcile white-space cascade using HISTORICAL attainment")
print("Instead of pipeline coverage, the white-space org evaluates")
print("'have they historically hit targets at this size?' by comparing")
print("the new cascaded quota against past 4Q NetNewACV attainment.\n")

# Use the same PipelineAdjuster but point pipeline_attr at historical
# attainment columns. Thresholds tightened: ratios cluster near 1.0x
# for historical performance (vs 1.5-3x for forward pipeline).
historical_adjuster = PipelineAdjuster(
    hierarchy_ws, ws_quotas,
    pipeline_attr=['Q1_NetNewACV', 'Q2_NetNewACV',
                   'Q3_NetNewACV', 'Q4_NetNewACV'],
)
historical_thresholds = {
    'NA':       {'healthy': 1.10, 'at_risk': 0.80},
    'EMEA':     {'healthy': 1.05, 'at_risk': 0.75},
    'APAC':     {'healthy': 1.00, 'at_risk': 0.70},
    '_default': {'healthy': 1.00, 'at_risk': 0.75},
}
ws_diagnosis = historical_adjuster.diagnose(historical_thresholds)
ws_diagnosis_path = os.path.join(OUT_DIR, 'output_whitespace_diagnosis.csv')
ws_diagnosis.to_csv(ws_diagnosis_path, index=False)

# Summary by risk status across the hierarchy
ws_summary = ws_diagnosis.groupby('Risk_Status').agg(
    Nodes=('Node', 'count'),
    Total_Quota=('Cascaded_Quota', 'sum'),
    Total_HistoricalAct=('Pipeline', 'sum'),
).reset_index().sort_values('Nodes', ascending=False)
print(f"Historical-attainment vs new cascaded quota — risk summary:")
print(ws_summary.to_string(index=False,
      formatters={'Total_Quota': '${:,.0f}'.format,
                  'Total_HistoricalAct': '${:,.0f}'.format}))
print(f"\nWrote {ws_diagnosis_path}")
print(f"\nReading: nodes flagged 'At Risk' or 'Critical' are those whose")
print(f"historical attainment is well below the new white-space target —")
print(f"i.e., the forward-looking plan asks them to step up significantly.")


# ======================================================================
# STEP 18 — Final summary
# ======================================================================
section(18, "Summary report")
print(f"Hierarchy:              {len(hierarchy.graph.nodes)} nodes "
      f"({len(leaves)} ICs across {len(set(df['Region']))} regions)")
print(f"Multi-metric cascade:   5 metrics blended ($50M -> ${ic_total:,.0f} "
      f"with hedging)")
print(f"Brand-new ICs handled:  {len(flagged)} reps got equal-share carve-out")
print(f"CRO overrides applied:  1 ({strategic_ic} pinned at "
      f"${quotas_with_override[strategic_ic]:,.0f})")
print(f"Pipeline diagnosis:     ran on multi-column sum across 3 columns")
print(f"Pipeline adjustments:   {adjusted_count} ICs redistributed within "
      f"managers (zero-sum)")
print(f"Commit reconciliation:  {len(reconciler.bias_weights)} managers "
      f"bias-corrected and blended with ML baseline")

print(f"\n--- Part B (white-space planning) ---")
print(f"Forward cascade:        3 forward metrics blended ($50M -> ${ws_ic_total:,.0f})")
print(f"Gated nodes:            {len(cascader_ws.gated_nodes)} "
      f"({len(ws_gated_leaves)} ICs + parents); got $0")
print(f"Whole-team gate demo:   {mgr_with_zero_team} + 4 ICs all $0 "
      f"(no unmigrated seats)")
print(f"Historical reconciler:  past-4Q-attainment vs new cascade")

print(f"\nOutputs written:        7 CSVs · 1 SQLite DB · 1 interactive HTML dashboard")
print(f"\nWalkthrough complete.")
