"""
Step-by-step walkthrough of b2b_revenue_forecasting (v0.7+).

Demonstrates every public capability end-to-end on the synthetic demo
dataset generated by examples/generate_demo_data.py:

  Step 1.  Load the CSV
  Step 2.  Build the hierarchy (with the brand-new IC column from CSV)
  Step 3.  Declare metrics + their direction (user input)
  Step 4.  Suggest weights from data (correlation magnitude)
  Step 5.  Override a suggested weight where domain disagrees
  Step 6.  Inspect the normalized-weights view (what stakeholders see)
  Step 7.  Sanity-check via exploratory direction inference
  Step 8.  Cascade quota with multi-metric blend + per-region hedge
           (v0.5.0: the un-hedged base layer comes free via base_quotas)
  Step 9.  Add a CRO override + show how the carve-out interacts
  Step 10. Diagnose pipeline health (multi-column pipeline)
  Step 11. Redistribute IC quotas based on pipeline coverage
  Step 12. Reconcile manager commits with historical bias quotients
  Step 13. Export all outputs to CSV (with hedge audit columns —
           no second cascade needed since v0.5.0)
  Step 14. Write outputs to a SQL database (SQLite example)
  Step 15. Generate an interactive HTML dashboard
  ── PART B: White-space planning (forward-looking cascade + gates) ──
  Step 16. Cascade with FORWARD-looking metrics + a hard gate
  Step 17. Gate fallback + per-depth reconciliation (v0.5.0 / issue #12)
  Step 18. Reconcile using HISTORICAL attainment (instead of pipeline)
  ── PART C: Batch cascading (v0.7.0) ──
  Step 19. cascade_many — one call for every (segment x quarter) combo
  Step 20. Summary report

Column-resolution note (v0.7.1, relevant to Steps 3-5):
  A MetricSpec finds its data in this order: explicit columns=[...] ->
  the Q1_<name>..Q<lookback>_<name> convention -> the plain column named
  exactly <name>. Specs returned by suggest_weights are directly usable;
  metrics with zero tree-wide signal trigger a loud warning.

Data-hygiene notes (v0.6.x, applied automatically in Step 2):
  - duplicate adjacent levels are auto-renamed (on_collision='suffix')
  - blank/'nan' string levels are treated as missing
  - the graph is DAG-validated; cycles raise HierarchyValidationError
  - metric values are coerced (numpy scalars, 'true'/'false', '$1,200');
    uncoercible cells warn and are treated as missing

Run from project root:
    python examples/walkthrough.py
"""
import warnings
import pandas as pd
import sys
sys.path.insert(0, '.')

from b2b_revenue_forecasting import (
    SalesHierarchy,
    QuotaCascader,
    PipelineAdjuster,
    CommitReconciler,
    MetricSpec,
    cascade_many,
    cascade_levels,
    route_targets,
    HedgeByDepth,
    Pin,
    apply_pins,
    redistribute,
    concentrate,
)

# Pretty separators for the printed walkthrough
H1 = '=' * 90
H2 = '-' * 90


def section(n, title):
    print(f"\n\n{H1}\nSTEP {n}: {title}\n{H1}")


def sub(text):
    print(f"\n{H2}\n{text}\n{H2}")


# ======================================================================
# STEP 1 — Load the CSV
# ======================================================================
section(1, "Load the analyst-uploaded CSV")
df = pd.read_csv('examples/data/demo_hierarchy.csv', keep_default_na=False)
print(f"Loaded {len(df)} IC rows from examples/data/demo_hierarchy.csv")
print(f"Columns ({len(df.columns)}): {list(df.columns)}")
print(f"\nFirst 2 rows (key columns only):")
print(df[['Region', 'IC', 'Q4_NetNewACV', 'Q4_CloudSeats',
         'LTM_ExpansionSpent', 'Q4_Has_Active_Cert',
         'Open_Pipeline', 'Is_Brand_New']].head(2).to_string(index=False))


# ======================================================================
# STEP 2 — Build the hierarchy with the brand-new column
# ======================================================================
section(2, "Build the SalesHierarchy (brand-new flag ingested from CSV)")
taxonomy = ['Global', 'Region', 'RVP', 'Director', 'Manager', 'IC']
metrics_cols = [
    'Q1_NetNewACV', 'Q2_NetNewACV', 'Q3_NetNewACV', 'Q4_NetNewACV',
    'Q1_CloudSeats', 'Q2_CloudSeats', 'Q3_CloudSeats', 'Q4_CloudSeats',
    'Q1_DCSeats', 'Q2_DCSeats', 'Q3_DCSeats', 'Q4_DCSeats',
    'LTM_ExpansionSpent',
    'Q1_Has_Active_Cert', 'Q2_Has_Active_Cert',
    'Q3_Has_Active_Cert', 'Q4_Has_Active_Cert',
    'Open_Pipeline', 'Late_Stage_Commit', 'Best_Case_Adds',
]

hierarchy = SalesHierarchy()
hierarchy.from_dataframe(
    df,
    path_cols=taxonomy,
    metrics_cols=metrics_cols,
    brand_new_col='Is_Brand_New',   # ingest the brand-new flag from CSV
)
print(f"Total nodes in DAG: {len(hierarchy.graph.nodes)}")
print(f"Individual Contributors (leaves): {len(hierarchy.get_leaves('Global_Corp'))}")
print(f"Regions:  {list(hierarchy.get_children('Global_Corp'))}")

# Show that the brand-new flag landed on the right ICs
flagged = [n for n in hierarchy.graph.nodes
           if hierarchy.graph.nodes[n].get('_is_brand_new')]
print(f"\nICs flagged brand-new via CSV: {len(flagged)}")
print(f"Examples: {flagged[:3]}")

# v0.7.2: read-only helpers — no need to touch hierarchy.graph directly
# (.graph is the canonical accessor everywhere; .hierarchy also works)
print(f"roots(): {hierarchy.roots()} · leaves(): {len(hierarchy.leaves())} ICs "
      f"· managers(): {len(hierarchy.managers())} "
      f"· max depth: {max(hierarchy.node_depths().values())}")

# Since v0.6.x, from_dataframe also hardens the build automatically:
#   - duplicate adjacent levels auto-rename (on_collision='suffix')
#   - blank / 'nan'-string levels are treated as missing
#   - metric cells are coerced ('true' -> True, '$1,200' -> 1200.0);
#     uncoercible values warn and become missing (never a silent 0)
#   - the finished graph is DAG-validated (cycles raise a clear error)
#   - v0.19.1: metrics that look repeated from an ancestor grain
#     (identical across leaf-sibling groups) trigger a warning
print("\nGraph validated as a DAG:",
      hierarchy.validate() is hierarchy)  # chainable; raises if cyclic


# ======================================================================
# STEP 3 — Declare metrics with USER-PROVIDED direction
# ======================================================================
section(3, "Declare which metrics drive cascading + their direction")
print("Direction is a DOMAIN decision: the analyst tells the package whether")
print("more-of-X means MORE quota (proportional) or LESS quota (inverse).")
print("The package never overrides this from data.\n")

declared_metrics = [
    MetricSpec('NetNewACV',       direction='proportional', weight=1.0, lookback=4),
    MetricSpec('CloudSeats',      direction='proportional', weight=1.0, lookback=4),
    MetricSpec('DCSeats',         direction='inverse',      weight=1.0, lookback=4),
    MetricSpec('ExpansionSpent',  direction='inverse',      weight=1.0,
               columns=['LTM_ExpansionSpent']),
    MetricSpec('Has_Active_Cert', direction='proportional', weight=1.0, lookback=4),
]
for m in declared_metrics:
    print(f"  {m.name:<18s} direction={m.direction:<13s} "
          f"lookback={m.lookback}  columns={m.resolved_columns()}")


# ======================================================================
# STEP 4 — Suggest weights via correlation (directions stay user's)
# ======================================================================
section(4, "Suggest weights from data (correlation magnitude)")
print("Pass the declared MetricSpecs to suggest_weights. Each metric is")
print("correlated against NetNewACV_4Q_sum; |correlation| becomes the")
print("suggested weight. Directions are preserved exactly as declared.\n")

# Aggregate the per-quarter boolean cert columns into a single 4Q sum
# (range 0..4 per IC) so it correlates cleanly against the dollar target.
df['Has_Cert_4Q_sum'] = (
    df[['Q1_Has_Active_Cert', 'Q2_Has_Active_Cert',
        'Q3_Has_Active_Cert', 'Q4_Has_Active_Cert']]
    .astype(int).sum(axis=1)
)

# Direction is REQUIRED on every candidate. All 4 secondary metrics go
# through the suggester so each weight is grounded in the data.
# v0.12.0 (issue #33): on tiny/degenerate slices where correlation is
# undefined, candidates now KEEP their declared weights by default
# (on_degenerate='proportional') instead of silently zeroing out and
# equal-splitting — see on_degenerate='equal'/'raise' for alternatives.
# (NetNewACV is the cascade target itself — correlating it with itself
# would always give 1.0, so we pin it manually as the anchor.)
candidates = [
    {'name': 'CloudSeats',      'column': 'CloudSeats_4Q_sum',
     'direction': 'proportional', 'lookback': 4},
    {'name': 'DCSeats',         'column': 'DCSeats_4Q_sum',
     'direction': 'inverse',      'lookback': 4},
    {'name': 'ExpansionSpent',  'column': 'LTM_ExpansionSpent',
     'columns': ['LTM_ExpansionSpent'],
     'direction': 'inverse',      'lookback': 1},
    {'name': 'Has_Active_Cert', 'column': 'Has_Cert_4Q_sum',
     'direction': 'proportional', 'lookback': 4},
]

with warnings.catch_warnings(record=True) as warning_log:
    warnings.simplefilter('always')
    suggested, report = MetricSpec.suggest_weights(
        df,
        target_column='NetNewACV_4Q_sum',
        candidate_metrics=candidates,
    )

# NOTE (v0.7.1): these suggested specs are directly usable in
# cascade_quota. Column resolution: explicit columns= wins -> Qi_<name>
# convention (used here) -> plain <name> column fallback. The 'column'
# field above only feeds the correlation math.
print("Suggested weights:")
for s in suggested:
    r = report[s.name]
    match_str = ('agrees' if r['direction_matches_data']
                 else 'DISAGREES — but user direction kept')
    print(f"  {s.name:<18s} direction={s.direction:<13s} "
          f"weight={s.weight:.3f}  corr={r['correlation']:+.3f}  ({match_str})")

if warning_log:
    print("\nWarnings emitted by suggest_weights:")
    for w in warning_log:
        print(f"  - {w.message}")
else:
    print("\nNo direction-mismatch warnings fired — data agrees with all directions.")


# ======================================================================
# STEP 5 — Override a suggested weight where domain knowledge disagrees
# ======================================================================
section(5, "Override a suggested weight (Pattern A: mutate after suggestion)")
print("Suppose DCSeats came back weak (0.067) but the RevOps team believes")
print("it's a more important headwind than the data shows for next quarter")
print("(maybe a known platform sunset). The analyst overrides just that")
print("weight — the rest stay data-driven.\n")

# Edit in place — suggested is a list of MetricSpec, fully mutable
for s in suggested:
    if s.name == 'DCSeats':
        before = s.weight
        s.weight = 0.4   # analyst's domain judgment
        print(f"  DCSeats weight: {before:.3f} (suggested) -> {s.weight:.3f} (overridden)")

# Pin the cascade target (NetNewACV) at the anchor weight of 1.0
cascade_metrics = [
    MetricSpec('NetNewACV', direction='proportional', weight=1.0, lookback=4),
    *suggested,
]

print("\nFinal cascade metric set:")
for m in cascade_metrics:
    print(f"  {m.name:<18s} direction={m.direction:<13s} weight={m.weight:.3f}")


# ======================================================================
# STEP 6 — Inspect the normalized-weights view
# ======================================================================
section(6, "Normalized-weights view (what stakeholders should actually see)")
print("Input weights don't sum to 1 — the package normalizes them at")
print("cascade time across the ACTIVE metrics (weight > 0). This is the")
print("table to show stakeholders: it answers 'how much does each signal")
print("actually pull the allocation?'\n")

print(MetricSpec.format_normalized_weights(cascade_metrics))

# Same data is also available as a DataFrame for further analysis
weights_df = MetricSpec.normalized_weights(cascade_metrics)
print(f"\nAvailable programmatically as a DataFrame:")
print(weights_df.to_string(index=False))


# ======================================================================
# STEP 7 — Sanity-check via exploratory direction inference
# ======================================================================
section(7, "Sanity-check: infer BOTH direction and weight from data")
print("This is a tool for exploration ONLY — it lets you confirm your")
print("domain-driven directions agree with the data sign.\n")
explored, exp_report = MetricSpec.suggest_directions_and_weights(
    df,
    target_column='NetNewACV_4Q_sum',
    candidate_metrics=candidates,
)
print("Data-inferred directions:")
for s in explored:
    r = exp_report[s.name]
    print(f"  {s.name:<18s} inferred={s.direction:<13s} "
          f"weight={s.weight:.3f}  (corr={r['correlation']:+.3f})")


# ======================================================================
# STEP 8 — Cascade with multi-metric blend + per-region hedge
# ======================================================================
section(8, "Cascade $50M with multi-metric blend + per-region hedge")
print("Hedge: NA aggressive 10%, EMEA + APAC standard 5%, Global 5%.")
print("Brand-new ICs are picked up automatically from the CSV column.\n")

cascader = QuotaCascader(hierarchy)
MACRO_TARGET = 50_000_000.0

per_node_hedge = {
    'Global_Corp': 1.05,
    'NA':   1.10,
    'EMEA': 1.05,
    'APAC': 1.05,
}

quotas = cascader.cascade_quota(
    'Global_Corp',
    MACRO_TARGET,
    hedge_multiplier=per_node_hedge,
    metrics=cascade_metrics,
    new_ic_attr='_is_brand_new',   # read flag from CSV-ingested attribute
)
# The normalized-weights table is auto-printed at the top of every
# multi-metric cascade. Same DataFrame is also accessible afterward:
#   cascader.weights_report  -> pd.DataFrame

# NEW in v0.5.0: every cascade also computes the UN-HEDGED base layer in
# the same call — no second run needed. hedged = base x hedge^depth.
quotas_unhedged = dict(cascader.base_quotas)

leaves = hierarchy.get_leaves('Global_Corp')
ic_total = sum(quotas[ic] for ic in leaves)
print(f"Macro target:                ${MACRO_TARGET:>15,.2f}")
print(f"Sum of all IC quotas:        ${ic_total:>15,.2f}")
print(f"Compounded overassignment:   {(ic_total/MACRO_TARGET - 1)*100:>14.2f}%")
print(f"Number of ICs:               {len(leaves):>15d}")

print(f"\nPer-region totals at the RVP layer:")
for region in ['NA', 'EMEA', 'APAC']:
    region_total = quotas.get(region, 0.0)
    print(f"  {region:<6s} cascaded quota: ${region_total:,.2f}")

print(f"\nSample IC quotas (3 veteran + 3 brand-new):")
veterans = [n for n in leaves if not hierarchy.graph.nodes[n].get('_is_brand_new')][:3]
brand_new = [n for n in leaves if hierarchy.graph.nodes[n].get('_is_brand_new')][:3]
for ic in veterans + brand_new:
    flag = ' (BRAND-NEW)' if hierarchy.graph.nodes[ic].get('_is_brand_new') else ''
    print(f"  {ic:<55s} ${quotas[ic]:>12,.2f}{flag}")


# ======================================================================
# STEP 9 — CRO override on a strategic hire
# ======================================================================
section(9, "Re-cascade with CRO override for a strategic hire")
print("CRO mandates IC_Mgr_Dir_RVP_NA_1_1_1_1 must carry exactly $1.2M")
print("regardless of what the algorithm would assign.\n")

strategic_ic = veterans[0]   # pick a real IC id for the demo
override = {strategic_ic: 1_200_000.0}
# v0.13.0 (issues #23/#28): pins work at ANY level (ICs, managers, jagged
# leaves) and carry a BASIS. "The rep must carry exactly $1.2M" is a
# final-number statement -> override_basis='cascaded'. The default
# ('base') pins the un-hedged plan number instead, with the hedged value
# derived via the node's compound hedge factor.
quotas_with_override = cascader.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=per_node_hedge,
    metrics=cascade_metrics,
    new_ic_attr='_is_brand_new',
    new_ic_overrides=override,
    override_basis='cascaded',
)
print(f"  {strategic_ic} algorithmic quota:   ${quotas[strategic_ic]:>12,.2f}")
print(f"  {strategic_ic} CRO-locked quota:    ${quotas_with_override[strategic_ic]:>12,.2f}")
print(f"  Manager total still preserved? Sum of that manager's ICs = "
      f"${sum(quotas_with_override[c] for c in hierarchy.get_children(list(hierarchy.graph.predecessors(strategic_ic))[0])):,.2f}")


# ======================================================================
# STEP 10 — Diagnose pipeline health (multi-column pipeline)
# ======================================================================
section(10, "Diagnose pipeline coverage (sums 3 pipeline columns per IC)")
print("Pipeline = Open_Pipeline + Late_Stage_Commit + Best_Case_Adds.")
print("Per-region risk thresholds — NA aggressive, APAC conservative.\n")

adjuster = PipelineAdjuster(
    hierarchy,
    quotas,
    pipeline_attr=['Open_Pipeline', 'Late_Stage_Commit', 'Best_Case_Adds'],
)

coverage_thresholds = {
    'NA':       {'healthy': 1.5, 'at_risk': 0.8},
    'EMEA':     {'healthy': 2.5, 'at_risk': 1.2},
    'APAC':     {'healthy': 3.0, 'at_risk': 1.5},
    '_default': {'healthy': 2.0, 'at_risk': 1.0},
}
diagnosis = adjuster.diagnose(coverage_thresholds)

# Summary by risk status across the whole org
risk_summary = diagnosis.groupby('Risk_Status').agg(
    Nodes=('Node', 'count'),
    Total_Quota=('Cascaded_Quota', 'sum'),
    Total_Pipeline=('Pipeline', 'sum'),
).sort_values('Nodes', ascending=False).reset_index()

print("Risk-status summary across ALL hierarchy nodes:")
print(risk_summary.to_string(index=False,
                              formatters={'Total_Quota': '${:,.0f}'.format,
                                          'Total_Pipeline': '${:,.0f}'.format}))

# Drill into IC-level rows for a single manager
sample_mgr = list({list(hierarchy.graph.predecessors(ic))[0]
                   for ic in veterans})[0]
mgr_ics = hierarchy.get_children(sample_mgr)
print(f"\nIC-level coverage under {sample_mgr}:")
print(diagnosis[diagnosis['Node'].isin(mgr_ics)]
      [['Node', 'Cascaded_Quota', 'Pipeline', 'Coverage_Ratio', 'Risk_Status']]
      .to_string(index=False,
                 formatters={'Cascaded_Quota': '${:,.0f}'.format,
                             'Pipeline': '${:,.0f}'.format,
                             'Coverage_Ratio': '{:.2f}x'.format}))


# ======================================================================
# STEP 11 — Redistribute IC quotas based on pipeline coverage
# ======================================================================
section(11, "Redistribute IC quotas based on pipeline health (zero-sum)")
print("Within each manager: ICs with low pipeline coverage shed quota to")
print("ICs with high coverage, capped at ±20% per IC. Manager totals are")
print("preserved exactly.\n")

# Lock the strategic hire so they aren't touched by redistribution
adjusted = adjuster.adjust(
    mode='redistribute',
    coverage_thresholds=coverage_thresholds,
    max_adjustment_pct=0.20,
    locked_nodes={strategic_ic},
)

# Count adjustments
adjusted_count = sum(1 for ic in leaves
                     if abs(adjusted.get(ic, 0) - quotas.get(ic, 0)) > 0.01)
print(f"ICs whose quota was adjusted: {adjusted_count} of {len(leaves)}")

# Verify zero-sum per manager
manager_nodes = [n for n in hierarchy.graph.nodes
                 if list(hierarchy.graph.successors(n))
                 and all(hierarchy.graph.out_degree(c) == 0
                         for c in hierarchy.graph.successors(n))]
biggest_delta_mgr = max(manager_nodes, key=lambda m: abs(
    sum(adjusted[ic] - quotas[ic] for ic in hierarchy.get_children(m))
))
delta = sum(adjusted[ic] - quotas[ic]
            for ic in hierarchy.get_children(biggest_delta_mgr))
print(f"Largest manager-level drift (should be ~$0): "
      f"${delta:,.2f} at {biggest_delta_mgr}")

# Show a few movers
movers = sorted(
    [(ic, quotas[ic], adjusted[ic], adjusted[ic] - quotas[ic]) for ic in leaves
     if abs(adjusted[ic] - quotas[ic]) > 0.01],
    key=lambda t: abs(t[3]),
    reverse=True,
)[:5]
print(f"\nTop 5 ICs by absolute redistribution:")
print(f"  {'IC':<50s} {'Original':>14s} {'Adjusted':>14s} {'Delta':>12s}")
for ic, orig, adj, d in movers:
    print(f"  {ic:<50s} ${orig:>12,.0f} ${adj:>12,.0f} {'+'if d>=0 else ''}${d:>10,.0f}")


# ======================================================================
# STEP 12 — Reconcile manager commits with historical bias
# ======================================================================
section(12, "Reconcile manager commits with historical bias quotients")
print("Each manager's history is read; their commit is auto-adjusted by")
print("their historical 'sandbagger / happy-ears' ratio.\n")

commit_history = pd.read_csv('examples/data/demo_commit_history.csv')
reconciler = CommitReconciler(commit_history)

print("Historical bias quotients:")
for mgr_id, bias in reconciler.bias_weights.items():
    label = ('sandbagger' if bias > 1.1 else
             'happy ears' if bias < 0.9 else 'truth-teller')
    print(f"  {mgr_id:<35s} bias = {bias:.2f}  ({label})")

print("\nReconciling Q1 commits ($300K per manager) with ML baseline of $320K:")
current_commit = 300_000.0
ml_forecast = 320_000.0
for mgr_id in reconciler.bias_weights:
    raw_adj = current_commit * reconciler.bias_weights[mgr_id]
    blended = reconciler.reconcile_forecast(mgr_id, current_commit, ml_forecast)
    print(f"  {mgr_id}")
    print(f"     Manager committed:     ${current_commit:,.0f}")
    print(f"     Bias-adjusted human:   ${raw_adj:,.0f}")
    print(f"     Blended with ML:       ${blended:,.0f}")


# ======================================================================
# STEP 13 — Export every output to CSV
# ======================================================================
import os
section(13, "Export all outputs to CSV (with hedge audit columns)")
print("Since v0.5.0 there's no need to run the cascade twice: the")
print("un-hedged baseline was captured from cascader.base_quotas at")
print("Step 8. The CSV gets both columns plus the dollar buffer and")
print("overassignment percentage per node. (If the quotas dict you're")
print("exporting came from the MOST RECENT cascade call, you can also")
print("just pass unhedged_quotas='auto'.)\n")

OUT_DIR = 'examples/data'
os.makedirs(OUT_DIR, exist_ok=True)

# quotas_unhedged was captured at Step 8 via cascader.base_quotas —
# the cascade at Step 9 (CRO override) overwrote base_quotas, which is
# why we snapshot it when the run we care about happens.

# 1) Cascaded quotas — every node at every level, both with and without hedge
cascaded_df = cascader.quotas_to_dataframe(
    quotas, level_names=taxonomy,
    unhedged_quotas=quotas_unhedged,    # adds 3 audit columns
)
cascaded_path = os.path.join(OUT_DIR, 'output_cascaded_quotas.csv')
cascaded_df.to_csv(cascaded_path, index=False)
print(f"[1/5] {cascaded_path}")
print(f"      rows: {len(cascaded_df)} (every node at every level)")
print(f"      columns: {list(cascaded_df.columns)}")
print(cascaded_df.head(8).to_string(index=False))

# NEW in v0.8.0 (issue #7): carry source attributes into the export —
# no manual merge. Join ANY frame onto the leaf rows (keyed on original
# ids, so it survives on_collision renames):
rep_directory = pd.DataFrame({
    'IC': leaves,
    'Rep_Name': [f"Rep {i + 1:03d}" for i in range(len(leaves))],
})
cascaded_with_meta = cascader.quotas_to_dataframe(
    quotas, level_names=taxonomy,
    source_df=rep_directory, source_join_col='IC',
)
ic_rows = cascaded_with_meta[cascaded_with_meta.is_leaf]
print(f"\n      v0.8.0 metadata join — IC rows now carry Rep_Name:")
print(ic_rows[['node_id', 'Rep_Name', 'cascaded_quota']]
      .head(3).to_string(index=False))
# (from_dataframe(metadata_cols=[...]) + quotas_to_dataframe(
#  metadata_cols=[...]) does the same for columns in the analyst CSV)
# v0.19.2 (#16): metadata_cols carries METRIC columns too — list
# knowledge_workers there and leaf rows emit its value even while an
# explicit MetricSpec uses the same column to drive the split; the
# cascade numbers are identical either way.

# 2) Normalized weights — what stakeholders see
weights_path = os.path.join(OUT_DIR, 'output_normalized_weights.csv')
cascader.weights_report.to_csv(weights_path, index=False)
print(f"\n[2/5] {weights_path}")
print(cascader.weights_report.to_string(index=False))

# 3) Pipeline diagnosis — coverage + risk status for every node
diagnosis_path = os.path.join(OUT_DIR, 'output_pipeline_diagnosis.csv')
diagnosis.to_csv(diagnosis_path, index=False)
print(f"\n[3/5] {diagnosis_path}")
print(f"      rows: {len(diagnosis)} (every node)")
print(diagnosis.head(5).to_string(index=False))

# 4) Redistributed quotas — original vs adjusted with deltas (IC level only)
redist_df = cascader.quotas_diff_to_dataframe(
    original=quotas, adjusted=adjusted, level_names=taxonomy,
)
redist_path = os.path.join(OUT_DIR, 'output_redistributed_quotas.csv')
redist_df.to_csv(redist_path, index=False)
print(f"\n[4/5] {redist_path}")
print(f"      rows: {len(redist_df)} (IC level)")
# Show the top 5 movers
top_movers = redist_df.reindex(
    redist_df['delta'].abs().sort_values(ascending=False).index
).head(5)
print(top_movers.to_string(index=False))

# 5) Commit reconciliation — bias quotients + blended forecasts
commits_input = pd.DataFrame({
    'Manager_ID': list(reconciler.bias_weights.keys()),
    'Current_Commit': [300_000.0] * len(reconciler.bias_weights),
    'Machine_Forecast': [320_000.0] * len(reconciler.bias_weights),
})
recon_df = reconciler.reconcile_all(
    commits_input,
    manager_col='Manager_ID',
    commit_col='Current_Commit',
    machine_col='Machine_Forecast',
)
recon_path = os.path.join(OUT_DIR, 'output_commit_reconciliation.csv')
recon_df.to_csv(recon_path, index=False)
print(f"\n[5/5] {recon_path}")
print(recon_df.to_string(index=False))


# ======================================================================
# STEP 14 — Write outputs to a SQL database (SQLite example)
# ======================================================================
import sqlite3
section(14, "Write outputs to a SQL database (SQLite example)")
print("Every output is already a DataFrame, so pandas' built-in to_sql()")
print("handles writes to ANY SQLAlchemy-compatible database (SQLite,")
print("Postgres, MySQL, Snowflake, BigQuery, Redshift, etc). Here we")
print("demo with SQLite — same pattern works for production DBs.\n")

# Pick a writable location for the SQLite DB. On most local filesystems
# OUT_DIR works fine; some sandboxes / network mounts don't support
# SQLite's file-locking, so fall back to the system tempdir.
import tempfile
preferred_db_path = os.path.join(OUT_DIR, 'cascade_results.db')
fallback_db_path = os.path.join(tempfile.gettempdir(), 'cascade_results.db')

def _try_write_sqlite(target_path):
    if os.path.exists(target_path):
        os.remove(target_path)
    tables = {
        'cascaded_quotas':       cascaded_df,
        'normalized_weights':    cascader.weights_report,
        'pipeline_diagnosis':    diagnosis,
        'redistributed_quotas':  redist_df,
        'commit_reconciliation': recon_df,
    }
    with sqlite3.connect(target_path) as conn:
        for name, frame in tables.items():
            frame.to_sql(name, conn, if_exists='replace', index=False)
            n = conn.execute(f'SELECT COUNT(*) FROM {name}').fetchone()[0]
            print(f"  wrote {n:>4d} rows to table `{name}`")
    return target_path

try:
    db_path = _try_write_sqlite(preferred_db_path)
    print(f"\nDatabase: {db_path}")
except (sqlite3.OperationalError, OSError, PermissionError) as e:
    print(f"  ({preferred_db_path} not writable: {e}; falling back to tempdir)")
    db_path = _try_write_sqlite(fallback_db_path)
    print(f"\nDatabase: {db_path}  (fallback location)")

# Smoke-test: read one row back to prove it's queryable
print(f"\nSmoke-test query — region totals from cascaded_quotas:")
with sqlite3.connect(db_path) as conn:
    rows = conn.execute(
        "SELECT level, node_id, cascaded_quota, unhedged_quota "
        "FROM cascaded_quotas WHERE depth = 1 ORDER BY cascaded_quota DESC"
    ).fetchall()
    for level, node, cascaded, unhedged in rows:
        print(f"  {level:<8s} {node:<6s} cascaded ${cascaded:>14,.2f}  "
              f"unhedged ${unhedged:>14,.2f}")

print(f"\nFor Postgres / Snowflake / etc, swap the sqlite3 connection for a")
print(f"SQLAlchemy engine and the same to_sql() calls work unchanged:")
print(f"  from sqlalchemy import create_engine")
print(f"  engine = create_engine('postgresql://user:pass@host/db')")
print(f"  cascaded_df.to_sql('cascaded_quotas', engine, if_exists='replace')")


# ======================================================================
# STEP 15 — Generate an interactive HTML dashboard
# ======================================================================
section(15, "Generate an interactive HTML dashboard")
print("Self-contained HTML file with Chart.js visualizations. Opens in")
print("any browser, shareable via email or intranet upload, no server")
print("required. Embeds all data inline as JSON.\n")

dashboard_path = os.path.join(OUT_DIR, 'cascade_dashboard.html')
cascader.to_html_dashboard(
    quotas,
    output_path=dashboard_path,
    title="Q1 Cascade Dashboard — $50M Multi-Metric Plan",
    macro_target=MACRO_TARGET,
    unhedged_quotas=quotas_unhedged,    # adds hedge-buffer comparison
    adjusted_quotas=adjusted,           # adds redistribution chart
    diagnosis=diagnosis,                # adds risk-status chart
)
print(f"Wrote dashboard: {dashboard_path}")
print(f"  size: {os.path.getsize(dashboard_path):,} bytes")
print(f"  charts: Region totals · Top 20 ICs · Top redistributions · Risk status")
print(f"  Open in any browser: file://{os.path.abspath(dashboard_path)}")


# ======================================================================
# ===== PART B — WHITE-SPACE PLANNING (alternative philosophy) =========
# ======================================================================
# Up to Step 15 we used "earned planning" — historical signals drive the
# cascade, current pipeline drives reconciliation. Some orgs flip this:
# they plan around FORWARD-looking opportunity ("what can be achieved")
# and reconcile against HISTORICAL signals ("how have they actually
# performed against past targets"). Steps 16–17 show that flow on the
# same dataset, using NEW columns the analyst added to the same CSV.

# ======================================================================
# STEP 16 — Forward-looking cascade with a hard gate
# ======================================================================
section(16, "Cascade with FORWARD-looking metrics + a hard gate")
print("Forward-looking metrics: current installed seats (proportional),")
print("knowledge workers per territory (proportional), LTM expansion")
print("spend (inverse — high spend dampens upside). Gate: unmigrated")
print("seats == 0 means '$0 migration quota' — no white space, no target.\n")

# Build a fresh hierarchy that ALSO ingests the new forward columns
white_space_metrics_cols = metrics_cols + [
    'Current_Seats_ProductX', 'Knowledge_Workers_Count', 'Unmigrated_Seats',
]
hierarchy_ws = SalesHierarchy()
hierarchy_ws.from_dataframe(
    df, path_cols=taxonomy, metrics_cols=white_space_metrics_cols,
    brand_new_col='Is_Brand_New',
)
cascader_ws = QuotaCascader(hierarchy_ws)

# Forward-looking metric slate (no historical attainment here)
forward_metrics = [
    MetricSpec('Current_Seats_ProductX',  direction='proportional',
               weight=1.0, columns=['Current_Seats_ProductX']),
    MetricSpec('Knowledge_Workers_Count', direction='proportional',
               weight=0.7, columns=['Knowledge_Workers_Count']),
    MetricSpec('LTM_ExpansionSpent',      direction='inverse',
               weight=0.5, columns=['LTM_ExpansionSpent']),  # dampener
]
# Gate: territories with zero unmigrated seats must get $0.
# v0.9.0: the PASS predicate is configurable via gate_mode —
#   default 'gt'  : pass iff value >  gate_threshold  (used here)
#   'ge'          : pass iff value >= threshold ("at least N seats")
#   'lt' / 'le'   : pass iff value BELOW threshold (gate churn-heavy reps)
#   'truthy'      : pass iff bool(value) (boolean entitlement flags)
gate_metrics = [
    MetricSpec('Unmigrated_Seats', columns=['Unmigrated_Seats']),
]

ws_quotas = cascader_ws.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=1.05,
    metrics=forward_metrics,
    gate_metrics=gate_metrics,
    new_ic_attr='_is_brand_new',
)

ws_leaves = hierarchy_ws.get_leaves('Global_Corp')
ws_ic_total = sum(ws_quotas[ic] for ic in ws_leaves)
ws_gated_leaves = [ic for ic in ws_leaves if ic in cascader_ws.gated_nodes]
ws_zero_leaves = [ic for ic in ws_leaves if ws_quotas[ic] == 0]

print(f"\nWhite-space cascade summary:")
print(f"  Macro target:        ${MACRO_TARGET:>12,.2f}")
print(f"  Sum of IC quotas:    ${ws_ic_total:>12,.2f}")
print(f"  Gated IC nodes:      {len(ws_gated_leaves):>4d}  (got $0 — no white space)")
print(f"  Non-gated $0 ICs:    {len(ws_zero_leaves) - len(ws_gated_leaves):>4d}")
print(f"  Funded IC nodes:     {len([ic for ic in ws_leaves if ws_quotas[ic] > 0]):>4d}")

# Show that the whole APAC subtree under Mgr_Dir_RVP_APAC_1_1_1 is gated
mgr_with_zero_team = 'Mgr_Dir_RVP_APAC_1_1_1'
if mgr_with_zero_team in cascader_ws.gated_nodes:
    mgr_team_ics = hierarchy_ws.get_children(mgr_with_zero_team)
    print(f"\n  Whole-subtree gate propagation example:")
    print(f"    {mgr_with_zero_team} (entire team fully migrated): "
          f"${ws_quotas.get(mgr_with_zero_team, 0):,.2f}")
    for ic in mgr_team_ics[:3]:
        print(f"      └─ {ic}: ${ws_quotas[ic]:,.2f}")
    print(f"      ({len(mgr_team_ics)} ICs total — all $0)")

# Export the cascaded quotas CSV with the is_gated column
ws_cascaded_df = cascader_ws.quotas_to_dataframe(ws_quotas, level_names=taxonomy)
ws_csv_path = os.path.join(OUT_DIR, 'output_whitespace_cascaded_quotas.csv')
ws_cascaded_df.to_csv(ws_csv_path, index=False)
# v0.17.0 (issue #34): the deterministic one-liner — split proportional
# to a single metric, no correlation, no suggest_weights. (Fixed-weight
# MetricSpecs were ALWAYS used as-is; this is the discoverable name.)
quick = QuotaCascader(hierarchy_ws).cascade_proportional(
    'Global_Corp', 1_000_000.0, metric='Current_Seats_ProductX',
    verbose=False)
seat_share = {r: quick[r] / 1_000_000.0 for r in ['NA', 'EMEA', 'APAC']}
print(f"\ncascade_proportional one-liner (seat-share split): "
      + " · ".join(f"{r} {s:.1%}" for r, s in seat_share.items()))

print(f"\nWrote {ws_csv_path}")
print(f"  columns: {list(ws_cascaded_df.columns)}")
print(f"  Sample gated IC rows (is_gated=True, cascaded_quota=0):")
print(ws_cascaded_df[ws_cascaded_df['is_gated'] & ws_cascaded_df['is_leaf']]
      .head(3).to_string(index=False))


# ======================================================================
# STEP 17 — Gate fallback + per-depth reconciliation (v0.5.0, issue #12)
# ======================================================================
section(17, "Gate fallback: fully-gated subtrees no longer strand the target")
print("Issue #12: pre-v0.5.0, if EVERY leaf under the cascade root failed")
print("the gate, the root was zeroed and the target silently vanished —")
print("or, patched at depth 0, depth 1+ summed short. Now the base layer")
print("reconciles to the target at EVERY depth.\n")

# (a) Per-depth reconciliation of the Part-A cascade's base layer.
#     Hedged quotas legitimately grow with depth, so reconcile the base.
print("(a) reconciliation_report on the Step-8 base layer ($50M):")
recon = cascader.reconciliation_report(
    quotas_unhedged, target=MACRO_TARGET, strict=True,
)
print(recon.to_string(index=False))
print("    strict=True raises AssertionError if any depth is short.")

# (b) The issue-#12 scenario: cascade a slice whose leaves are ALL gated.
#     Mgr_Dir_RVP_APAC_1_1_1's territories have zero unmigrated seats.
#     Pre-0.5.0 this returned all-$0 (target lost). Default fallback
#     ('redistribute') relaxes the gate as a last resort so the target
#     still reaches ICs and every depth reconciles.
print(f"\n(b) Cascade $1M into fully-gated subtree {mgr_with_zero_team}:")
SLICE_TARGET = 1_000_000.0
slice_quotas = cascader_ws.cascade_quota(
    mgr_with_zero_team, SLICE_TARGET,
    metrics=forward_metrics,
    gate_metrics=gate_metrics,
    verbose=False,                      # gate_fallback='redistribute' is default
)
slice_ics = hierarchy_ws.get_children(mgr_with_zero_team)
print(f"    Root keeps target:  ${slice_quotas[mgr_with_zero_team]:,.2f} "
      f"(never gated to $0)")
for ic in slice_ics:
    relaxed = ' (gate relaxed — last resort)' if ic in cascader_ws.gate_relaxed_nodes else ''
    print(f"      └─ {ic}: ${slice_quotas[ic]:,.2f}{relaxed}")
print(f"    IC sum = ${sum(slice_quotas[ic] for ic in slice_ics):,.2f} "
      f"== target — nothing stranded")

# (c) The explicit opt-outs, for orgs that DON'T want last-resort funding:
print(f"\n(c) gate_fallback='strand_at_root' — keep the money visible instead:")
strand_quotas = cascader_ws.cascade_quota(
    mgr_with_zero_team, SLICE_TARGET,
    metrics=forward_metrics,
    gate_metrics=gate_metrics,
    gate_fallback='strand_at_root',
    verbose=False,
)
print(f"    Root holds ${strand_quotas[mgr_with_zero_team]:,.2f}; ICs get $0")
print(f"    cascader.unallocated       = ${cascader_ws.unallocated:,.2f}")
print(f"    cascader.unallocated_nodes = {cascader_ws.unallocated_nodes}")
print(f"    (quotas_to_dataframe adds an is_unallocated column)")
print(f"    gate_fallback='error' would raise GateAllocationError instead.")

# NEW in v0.10.0 (issue #10): the whole gating story in ONE call.
grep_ = cascader_ws.gating_report()
print(f"\n    gating_report() for the strand run:")
print(f"      gated_count:        {grep_['gated_count']}")
print(f"      gated_leaf_ids:     {grep_['gated_leaf_ids']}")
print(f"      unallocated_amount: ${grep_['unallocated_amount']:,.2f}")
print(f"      leaf_base_sum:      ${grep_['leaf_base_sum']:,.2f}")
print(f"      base_gap:           ${grep_['base_gap']:,.2f}")
print(f"      reconciles:         {grep_['reconciles']} "
      f"(every dollar on an IC or explicitly unallocated)")

# Restore the Part-B full cascade state for the steps below (the slice
# cascades above overwrote cascader_ws diagnostics/base_quotas).
ws_quotas = cascader_ws.cascade_quota(
    'Global_Corp', MACRO_TARGET,
    hedge_multiplier=1.05,
    metrics=forward_metrics,
    gate_metrics=gate_metrics,
    new_ic_attr='_is_brand_new',
    verbose=False,
)
print(f"\n(d) Part-B base layer also reconciles at every depth despite gates:")
print(cascader_ws.reconciliation_report(
    cascader_ws.base_quotas, target=MACRO_TARGET, strict=True,
).to_string(index=False))


# ======================================================================
# STEP 18 — Reconcile using HISTORICAL attainment (no current pipeline)
# ======================================================================
section(18, "Reconcile white-space cascade using HISTORICAL attainment")
print("Instead of pipeline coverage, the white-space org evaluates")
print("'have they historically hit targets at this size?' by comparing")
print("the new cascaded quota against past 4Q NetNewACV attainment.\n")

# Use the same PipelineAdjuster but point pipeline_attr at historical
# attainment columns. Thresholds tightened: ratios cluster near 1.0x
# for historical performance (vs 1.5-3x for forward pipeline).
historical_adjuster = PipelineAdjuster(
    hierarchy_ws, ws_quotas,
    pipeline_attr=['Q1_NetNewACV', 'Q2_NetNewACV',
                   'Q3_NetNewACV', 'Q4_NetNewACV'],
)
historical_thresholds = {
    'NA':       {'healthy': 1.10, 'at_risk': 0.80},
    'EMEA':     {'healthy': 1.05, 'at_risk': 0.75},
    'APAC':     {'healthy': 1.00, 'at_risk': 0.70},
    '_default': {'healthy': 1.00, 'at_risk': 0.75},
}
ws_diagnosis = historical_adjuster.diagnose(historical_thresholds)
ws_diagnosis_path = os.path.join(OUT_DIR, 'output_whitespace_diagnosis.csv')
ws_diagnosis.to_csv(ws_diagnosis_path, index=False)

# Summary by risk status across the hierarchy
ws_summary = ws_diagnosis.groupby('Risk_Status').agg(
    Nodes=('Node', 'count'),
    Total_Quota=('Cascaded_Quota', 'sum'),
    Total_HistoricalAct=('Pipeline', 'sum'),
).reset_index().sort_values('Nodes', ascending=False)
print(f"Historical-attainment vs new cascaded quota — risk summary:")
print(ws_summary.to_string(index=False,
      formatters={'Total_Quota': '${:,.0f}'.format,
                  'Total_HistoricalAct': '${:,.0f}'.format}))
print(f"\nWrote {ws_diagnosis_path}")
print(f"\nReading: nodes flagged 'At Risk' or 'Critical' are those whose")
print(f"historical attainment is well below the new white-space target —")
print(f"i.e., the forward-looking plan asks them to step up significantly.")


# ======================================================================
# ===== PART C — BATCH CASCADING (v0.7.0) ==============================
# ======================================================================
# Steps 8-18 cascaded ONE target at a time. Real planning runs cascade
# many targets across many segments (regions, products, sales types) for
# many quarters. cascade_many wraps the whole loop: prepare each
# combination once, cascade every matching target row against it, and
# return tidy long frames tagged with the group keys.

# ======================================================================
# STEP 19 — cascade_many: every (region x quarter) in one call
# ======================================================================
section(19, "PART C — cascade_many: every (region x quarter) in one call")
print("One row per cascade in target_df: Region + fiscal_quarter + target.")
print("fiscal_quarter is NOT a group key, so quarters reuse each region's")
print("prepared hierarchy ('prepare once / cascade many').\n")

regional_targets = pd.DataFrame([
    {'Region': 'NA',   'fiscal_quarter': 1, 'q_target': 25_000_000.0},
    {'Region': 'EMEA', 'fiscal_quarter': 1, 'q_target': 12_000_000.0},
    {'Region': 'APAC', 'fiscal_quarter': 1, 'q_target': 13_000_000.0},
    {'Region': 'NA',   'fiscal_quarter': 2, 'q_target': 27_500_000.0},
    {'Region': 'EMEA', 'fiscal_quarter': 2, 'q_target': 13_200_000.0},
    {'Region': 'APAC', 'fiscal_quarter': 2, 'q_target': 14_300_000.0},
])

quotas_long, weights_long = cascade_many(
    df,                                  # the SAME analyst CSV, unchanged
    regional_targets,
    group_keys=['Region'],
    target_col='q_target',
    taxonomy=taxonomy,
    metrics=cascade_metrics,             # Part A's blended slate
    # v0.11.0 (issue #13): per-DEPTH hedge — impossible with a per-node
    # dict here, since cascade_many builds each hierarchy internally.
    # Deepest managers (children are ICs) carry 10%, the level above 5%.
    hedge_multiplier=HedgeByDepth(from_leaves={1: 1.10, 2: 1.05}),
    # v0.15.0 (issue #14): gate_metrics also accepts a CALLABLE evaluated
    # per combination — e.g. gate only one sales type:
    #   gate_metrics=lambda g: DC_GATE if g['Region'] == 'NA' else None
    # v0.19.0 (issue #35): metrics= accepts the same shape for MIXED
    # weight strategies — fix some combos' slates verbatim, let others
    # use suggest_config:
    #   metrics=lambda g: DC_ONLY if g['Region'] == 'NA' else None
)

n_cascades = quotas_long.groupby(['Region', 'fiscal_quarter']).ngroups
print(f"Cascades run:        {n_cascades} (3 regions x 2 quarters)")
print(f"quotas_long rows:    {len(quotas_long)} "
      f"(every node of every cascade, tagged with Region + quarter)")
print(f"weights_long rows:   {len(weights_long)} (metric slate per region)")

print(f"\nSample rows (NA, Q1, top of tree):")
sample = quotas_long[(quotas_long.Region == 'NA')
                     & (quotas_long.fiscal_quarter == 1)
                     & (quotas_long.depth <= 2)]
print(sample[['Region', 'fiscal_quarter', 'depth', 'level', 'node_id',
              'cascaded_quota', 'base_quota']].head(6).to_string(index=False))

print(f"\nBase layer reconciles per cascade (sum of IC base_quota == target):")
ic_check = (quotas_long[quotas_long.is_leaf]
            .groupby(['Region', 'fiscal_quarter'])
            .agg(target=('q_target', 'first'), ic_base_sum=('base_quota', 'sum')))
print(ic_check.to_string(
    formatters={'target': '${:,.0f}'.format, 'ic_base_sum': '${:,.2f}'.format}))

batch_path = os.path.join(OUT_DIR, 'output_batch_cascaded_quotas.csv')
quotas_long.to_csv(batch_path, index=False)
print(f"\nWrote {batch_path}")

# NEW in v0.14.0 (issues #25/#26/#32): targets with NO hierarchy branch
# are returned as DATA — and can be routed onto named recipients.
print(f"\n--- Routing targets with no hierarchy branch (v0.14.0) ---")
gov_row = pd.DataFrame([{'Region': 'Government', 'fiscal_quarter': 1,
                         'q_target': 500_000.0}])   # no Government subtree!
import warnings as _warnings
with _warnings.catch_warnings():
    _warnings.simplefilter('ignore')
    q_gov, _, dropped = cascade_many(
        df, pd.concat([regional_targets, gov_row], ignore_index=True),
        group_keys=['Region'], target_col='q_target', taxonomy=taxonomy,
        metrics=cascade_metrics, hedge_multiplier=HedgeByDepth(
            from_leaves={1: 1.10, 2: 1.05}),
        return_dropped=True,
    )
print(f"Dropped targets: {len(dropped)} row(s), "
      f"${dropped['q_target'].sum():,.2f} "
      f"({dropped['Region'].iloc[0]}: {dropped['reason'].iloc[0][:48]}...)")

gov_recipients = sorted(
    q_gov[(q_gov.Region == 'NA') & (q_gov.fiscal_quarter == 1)
          & q_gov.is_leaf].node_id)[:3]
routed = route_targets(
    dropped, q_gov, recipients=gov_recipients, target_col='q_target',
    recipient_keys={'Region': 'NA', 'fiscal_quarter': 1},
    split='base_quota',            # proportional to existing capacity
)
leaf_routed = routed[routed.node_id.isin(gov_recipients)]
print(f"Routed onto {len(gov_recipients)} named NA reps "
      f"(split by base_quota, tagged Region='Government'):")
print(leaf_routed[['node_id', 'base_quota', 'cascaded_quota']]
      .to_string(index=False))
print(f"Routed base per depth all equal $500,000: "
      f"{(abs(routed.groupby('depth')['base_quota'].sum() - 500_000) < 0.05).all()}")
# full plan = pd.concat([q_gov, routed]) — additive by construction

# NEW in v0.16.0 (issues #22/#31/#24): pin a node to an EXACT TOTAL
# across every cascade it appears in, conserved at the parent.
print(f"\n--- Aggregate pins across cascades (v0.16.0) ---")
pin_ic = gov_recipients[0]
before = quotas_long[quotas_long.node_id == pin_ic]['base_quota'].sum()
pinned_df, feasibility = apply_pins(
    quotas_long,
    pins=[Pin(pin_ic, 500_000.0)],          # total across all 6 cascades
    freeze_nodes=[gov_recipients[1]],        # this rep never absorbs (#24)
)
after = pinned_df[pinned_df.node_id == pin_ic]['base_quota'].sum()
print(f"{pin_ic}: ${before:,.2f} -> ${after:,.2f} total "
      f"(baseline mix preserved across Region x quarter)")
print(feasibility[['pin_node', 'pin_type', 'requested_total',
                   'achieved_total', 'unabsorbed', 'feasible']]
      .to_string(index=False))
frozen_same = (pinned_df[pinned_df.node_id == gov_recipients[1]]['base_quota']
               .reset_index(drop=True)
               .equals(quotas_long[quotas_long.node_id == gov_recipients[1]]
                       ['base_quota'].reset_index(drop=True)))
print(f"Frozen rep untouched: {frozen_same} · "
      f"is_pinned rows: {int(pinned_df['is_pinned'].sum())}")
# v0.20.0 (#39): the subtree rescale is protection-aware — descendants
# pinned by another Pin, in freeze_nodes, or in Pin.exclude keep their
# values while free siblings stretch (pin order no longer matters), and
# absorption is weighted by FREE capacity. If protected mass exceeds a
# pin, the feasibility report's subtree_shortfall column says so.
# v0.21.0 (#40): no row_keys needed here — cascade_many stamps the
# cascade identity on .attrs['cascade_row_keys'] and apply_pins reads
# it; wrong/poisoned keys now raise (naming the per-node columns)
# instead of silently downgrading manager pins to leaf pins.
# v0.22.0 (#41): pin LIST order never matters — pins apply in
# canonical depth order (managers before leaves) internally, so the
# whole output frame is identical for any ordering; the feasibility
# report stays in your list order.
# v0.25.0 (#48): pins that match ZERO rows (a product a region doesn't
# sell) no longer have to abort the batch — apply_pins(...,
# on_missing='skip'|'warn') records them in the feasibility report
# (skipped=True, reason='node_absent'|'empty_scope') and drops them
# entirely (no ghost protection side-effects).
# v0.22.1 (#42): "remainder to the unpinned sibling" is plain
# composition — [Pin('T1', x), Pin('T2', y)] sends the leftover to the
# unpinned teams at baseline proportions (add Pin(parent, total) to fix
# the envelope too). No remainder-team computation needed.

# NEW in v0.23.0 (issue #43): redistribute() — move a node's scoped
# quota to its siblings, reshaping BOTH subtrees at every depth.
# Thin sugar over apply_pins: it writes the pins for you.
print(f"\n--- Cross-sibling redistribution (v0.23.0) ---")
donor = quotas_long[quotas_long.depth == 1]['node_id'].iloc[0]
red_df, red_report = redistribute(quotas_long, donor)
print(f"redistribute('{donor}') -> source zeroed, siblings grew "
      f"proportionally:")
print(red_report[['node', 'role', 'baseline_total', 'achieved_total',
                  'exact']].to_string(index=False))

# NEW in v0.24.0 (issue #47): concentrate() — the inverse: collapse
# the siblings back ONTO one node (zeroing them), same report contract.
# (v0.25.1: also closes #29 'route 100% to a single child' — survivor
# gets the full pool, no leak — and #44 'concentrate onto one team'.)
print(f"\n--- Concentrate onto one sibling (v0.24.0) ---")
con_df, con_report = concentrate(quotas_long, donor)
print(f"concentrate('{donor}') -> siblings zeroed, '{donor}' holds the "
      f"whole group:")
print(con_report[['node', 'role', 'baseline_total', 'achieved_total',
                  'exact']].to_string(index=False))

# NEW in v0.18.0 (issue #30): level-by-level cascading with DIFFERENT
# behavior per transition — e.g. split Region->RVP by NetNewACV but
# RVP->Director by CloudSeats, hedging only the second step.
print(f"\n--- Level-by-level cascading (v0.18.0) ---")
lvl = cascade_levels(
    df, pd.DataFrame([{'Region': 'NA', 'q_target': 10_000_000.0}]),
    taxonomy=['Region', 'RVP', 'Director'],
    target_col='q_target',
    level_kwargs=[
        dict(metrics=[MetricSpec('NetNewACV', direction='proportional',
                                 weight=1.0, lookback=4)]),
        dict(metrics=[MetricSpec('CloudSeats', direction='proportional',
                                 weight=1.0, lookback=4)],
             hedge_multiplier=1.05),
    ])
print(lvl[lvl.level != 'Region']
      [['level', 'node_id', 'parent', 'base_quota', 'cascaded_quota']]
      .head(6).to_string(index=False))
by_level = lvl.groupby('level')['base_quota'].sum()
print(f"Base conserved at every level: "
      f"{(abs(by_level - 10_000_000.0) < 0.05).all()} "
      f"(RVPs split by ACV, Directors by CloudSeats +5% hedge)")


# ======================================================================
# STEP 20 — Final summary
# ======================================================================
section(20, "Summary report")
print(f"Hierarchy:              {len(hierarchy.graph.nodes)} nodes "
      f"({len(leaves)} ICs across {len(set(df['Region']))} regions)")
print(f"Multi-metric cascade:   5 metrics blended ($50M -> ${ic_total:,.0f} "
      f"with hedging)")
print(f"Brand-new ICs handled:  {len(flagged)} reps got equal-share carve-out")
print(f"CRO overrides applied:  1 ({strategic_ic} pinned at "
      f"${quotas_with_override[strategic_ic]:,.0f})")
print(f"Pipeline diagnosis:     ran on multi-column sum across 3 columns")
print(f"Pipeline adjustments:   {adjusted_count} ICs redistributed within "
      f"managers (zero-sum)")
print(f"Commit reconciliation:  {len(reconciler.bias_weights)} managers "
      f"bias-corrected and blended with ML baseline")

print(f"\n--- Part B (white-space planning) ---")
print(f"Forward cascade:        3 forward metrics blended ($50M -> ${ws_ic_total:,.0f})")
print(f"Gated nodes:            {len(cascader_ws.gated_nodes)} "
      f"({len(ws_gated_leaves)} ICs + parents); got $0")
print(f"Whole-team gate demo:   {mgr_with_zero_team} + 4 ICs all $0 "
      f"(no unmigrated seats)")
print(f"Historical reconciler:  past-4Q-attainment vs new cascade")

print(f"\n--- Part C (batch cascading, v0.7.0) ---")
print(f"cascade_many:           {n_cascades} cascades (3 regions x 2 quarters) "
      f"in one call")
print(f"Output:                 tidy long df, {len(quotas_long)} rows, "
      f"group-key tagged, base layer reconciled")

print(f"\nOutputs written:        8 CSVs · 1 SQLite DB · 1 interactive HTML dashboard")
print(f"\nWalkthrough complete.")
