"""
Self-contained HTML dashboard template for visualizing cascade results.

Used by QuotaCascader.to_html_dashboard(). The HTML uses Chart.js loaded
from CDN (https://cdn.jsdelivr.net/npm/chart.js) and embeds the cascade
data inline as a JSON payload — no server, no build step, no extra deps.
The generated file opens in any browser and is shareable via email,
attachment, intranet upload, etc.
"""

DASHBOARD_HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>__TITLE__</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.0/dist/chart.umd.js"></script>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    background: #f7f8fa;
    color: #1d2433;
    line-height: 1.5;
  }
  .container { max-width: 1280px; margin: 0 auto; padding: 28px 28px 60px; }
  header { margin-bottom: 24px; }
  header .eyebrow { color: #2f5cda; font-weight: 600; font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; }
  header h1 { font-size: 26px; margin: 6px 0 0; }
  header .meta { display: flex; flex-wrap: wrap; gap: 18px; color: #5c6677; font-size: 13px; margin-top: 8px; }
  .summary {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 14px;
    margin: 18px 0 24px;
  }
  .summary .stat {
    background: #fff;
    border: 1px solid #e2e6ee;
    border-radius: 8px;
    padding: 14px 16px;
  }
  .summary .label { color: #5c6677; font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; font-weight: 600; }
  .summary .value { font-size: 20px; font-weight: 700; margin-top: 6px; }
  .summary .sub { color: #5c6677; font-size: 12px; margin-top: 2px; }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(450px, 1fr));
    gap: 18px;
  }
  .card {
    background: #fff;
    border: 1px solid #e2e6ee;
    border-radius: 10px;
    padding: 18px 20px;
  }
  .card h2 { margin: 0 0 4px; font-size: 16px; }
  .card .subtitle { color: #5c6677; font-size: 12px; margin: 0 0 14px; }
  .chart-container { position: relative; height: 320px; }
  .chart-container.tall { height: 460px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  table th, table td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eef0f4; }
  table th { color: #5c6677; font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.06em; }
  table td.num { text-align: right; font-variant-numeric: tabular-nums; }
  footer { margin-top: 32px; color: #5c6677; font-size: 12px; }
</style>
</head>
<body>
<div class="container">

  <header>
    <div class="eyebrow">b2b_revenue_forecasting · dashboard</div>
    <h1>__TITLE__</h1>
    <div class="meta">
      <span>Generated: <strong id="meta-generated"></strong></span>
      <span>ICs: <strong id="meta-ics"></strong></span>
      <span>Macro target: <strong id="meta-target"></strong></span>
    </div>
  </header>

  <div class="summary" id="summary-cards"></div>

  <div class="grid">
    <div class="card">
      <h2>Quota by region</h2>
      <p class="subtitle">Cascaded quota (with hedging) per region; unhedged base shown when available.</p>
      <div class="chart-container"><canvas id="chartRegion"></canvas></div>
    </div>

    <div class="card">
      <h2>Top 20 IC quotas</h2>
      <p class="subtitle">Largest individual contributor allocations after cascading.</p>
      <div class="chart-container tall"><canvas id="chartTopICs"></canvas></div>
    </div>

    <div class="card" id="card-redist" style="display:none;">
      <h2>Top redistributions</h2>
      <p class="subtitle">Original vs adjusted quota after pipeline-health redistribution (zero-sum per manager).</p>
      <div class="chart-container tall"><canvas id="chartRedist"></canvas></div>
    </div>

    <div class="card" id="card-coverage" style="display:none;">
      <h2>Pipeline coverage by risk status</h2>
      <p class="subtitle">Count of nodes in each risk bucket from PipelineAdjuster.diagnose().</p>
      <div class="chart-container"><canvas id="chartRisk"></canvas></div>
    </div>

    <div class="card" id="card-table" style="display:none;">
      <h2>Per-region summary</h2>
      <p class="subtitle">Cascaded quota, unhedged base, hedge buffer.</p>
      <table id="regionTable">
        <thead><tr><th>Region</th><th class="num">Cascaded</th><th class="num">Unhedged</th><th class="num">Buffer</th><th class="num">Over %</th></tr></thead>
        <tbody></tbody>
      </table>
    </div>
  </div>

  <footer>Self-contained HTML — Chart.js loaded from CDN. No server required. Generated by <code>QuotaCascader.to_html_dashboard()</code>.</footer>
</div>

<script>
const DATA = __PAYLOAD__;

// Helpers
const fmt$ = v => '$' + Math.round(v).toLocaleString();
const fmtCompact = v => {
  const abs = Math.abs(v);
  if (abs >= 1e9) return '$' + (v/1e9).toFixed(2) + 'B';
  if (abs >= 1e6) return '$' + (v/1e6).toFixed(2) + 'M';
  if (abs >= 1e3) return '$' + (v/1e3).toFixed(1) + 'K';
  return '$' + v.toFixed(0);
};
const fmtPct = v => (v*100).toFixed(1) + '%';

document.getElementById('meta-generated').textContent = DATA.meta.generated;
document.getElementById('meta-ics').textContent = DATA.meta.ic_count.toLocaleString();
document.getElementById('meta-target').textContent = fmt$(DATA.meta.macro_target);

// Summary stat cards
const summaryEl = document.getElementById('summary-cards');
DATA.meta.summary_cards.forEach(card => {
  const div = document.createElement('div');
  div.className = 'stat';
  div.innerHTML = `<div class="label">${card.label}</div><div class="value">${card.value}</div>${card.sub ? `<div class="sub">${card.sub}</div>` : ''}`;
  summaryEl.appendChild(div);
});

// Chart defaults
Chart.defaults.font.family = '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif';
Chart.defaults.color = '#1d2433';
Chart.defaults.borderColor = '#e2e6ee';

const PALETTE = {
  primary: '#2f5cda',
  primarySoft: 'rgba(47,92,218,0.18)',
  accent: '#2a9d8f',
  warning: '#e9c46a',
  danger: '#d62828',
  neutral: '#94a3b8',
};

// Chart 1: Region totals
const regionLabels = DATA.regions.map(r => r.region);
const regionDatasets = [{
  label: 'Cascaded quota',
  data: DATA.regions.map(r => r.cascaded),
  backgroundColor: PALETTE.primary,
}];
if (DATA.regions.some(r => r.unhedged != null)) {
  regionDatasets.unshift({
    label: 'Unhedged base',
    data: DATA.regions.map(r => r.unhedged ?? 0),
    backgroundColor: PALETTE.primarySoft,
  });
}
new Chart(document.getElementById('chartRegion'), {
  type: 'bar',
  data: { labels: regionLabels, datasets: regionDatasets },
  options: {
    responsive: true, maintainAspectRatio: false,
    scales: { y: { ticks: { callback: v => fmtCompact(v) }, beginAtZero: true } },
    plugins: {
      tooltip: { callbacks: { label: ctx => `${ctx.dataset.label}: ${fmt$(ctx.parsed.y)}` } },
      legend: { position: 'top', align: 'end' },
    },
  },
});

// Chart 2: Top 20 ICs (horizontal bar)
new Chart(document.getElementById('chartTopICs'), {
  type: 'bar',
  data: {
    labels: DATA.top_ics.map(d => d.node_id),
    datasets: [{
      label: 'Cascaded quota',
      data: DATA.top_ics.map(d => d.cascaded_quota),
      backgroundColor: PALETTE.primary,
    }],
  },
  options: {
    indexAxis: 'y', responsive: true, maintainAspectRatio: false,
    scales: { x: { ticks: { callback: v => fmtCompact(v) }, beginAtZero: true } },
    plugins: {
      legend: { display: false },
      tooltip: { callbacks: { label: ctx => fmt$(ctx.parsed.x) } },
    },
  },
});

// Chart 3: Top redistributions (if data provided)
if (DATA.redistributions && DATA.redistributions.length > 0) {
  document.getElementById('card-redist').style.display = 'block';
  new Chart(document.getElementById('chartRedist'), {
    type: 'bar',
    data: {
      labels: DATA.redistributions.map(d => d.node_id),
      datasets: [
        { label: 'Original', data: DATA.redistributions.map(d => d.original), backgroundColor: PALETTE.neutral },
        { label: 'Adjusted', data: DATA.redistributions.map(d => d.adjusted), backgroundColor: PALETTE.accent },
      ],
    },
    options: {
      indexAxis: 'y', responsive: true, maintainAspectRatio: false,
      scales: { x: { ticks: { callback: v => fmtCompact(v) }, beginAtZero: true } },
      plugins: {
        legend: { position: 'top', align: 'end' },
        tooltip: { callbacks: { label: ctx => `${ctx.dataset.label}: ${fmt$(ctx.parsed.x)}` } },
      },
    },
  });
}

// Chart 4: Risk status counts (if data provided)
if (DATA.risk_counts && DATA.risk_counts.length > 0) {
  document.getElementById('card-coverage').style.display = 'block';
  const riskColors = { 'Healthy': PALETTE.accent, 'Moderate': PALETTE.warning, 'At Risk': '#f4a261', 'Critical': PALETTE.danger };
  new Chart(document.getElementById('chartRisk'), {
    type: 'bar',
    data: {
      labels: DATA.risk_counts.map(d => d.status),
      datasets: [{
        label: 'Node count',
        data: DATA.risk_counts.map(d => d.count),
        backgroundColor: DATA.risk_counts.map(d => riskColors[d.status] || PALETTE.neutral),
      }],
    },
    options: {
      responsive: true, maintainAspectRatio: false,
      scales: { y: { beginAtZero: true, ticks: { precision: 0 } } },
      plugins: { legend: { display: false } },
    },
  });
}

// Region summary table (if unhedged data available)
if (DATA.regions.some(r => r.unhedged != null)) {
  document.getElementById('card-table').style.display = 'block';
  const tbody = document.querySelector('#regionTable tbody');
  DATA.regions.forEach(r => {
    const buffer = r.cascaded - (r.unhedged || 0);
    const overPct = r.unhedged ? buffer / r.unhedged : 0;
    const tr = document.createElement('tr');
    tr.innerHTML = `<td>${r.region}</td><td class="num">${fmt$(r.cascaded)}</td><td class="num">${fmt$(r.unhedged || 0)}</td><td class="num">${fmt$(buffer)}</td><td class="num">${fmtPct(overPct)}</td>`;
    tbody.appendChild(tr);
  });
}
</script>
</body>
</html>
"""
