import pandas as pd
from typing import List, Dict, Any
import math
import uuid

class SellerAssignmentMatrix:
    """
    Handles mapping different types of sellers (AEs, SEs, SDRs) to optimized territories.
    Supports 1:1, 1:N, and N:1 coverage models.
    """
    
    def __init__(self, territories: List[str]):
        """
        Args:
            territories: List of all unique territory IDs generated by the allocator.
        """
        self.territories = sorted(territories)
        self.roles = {}  # type: Dict[str, Dict[str, Any]]
        self.assignments = [] # List of assignment records
        
    def add_role(self, role_name: str, territories_per_seller: float):
        """
        Registers a seller role and its coverage model.
        
        Args:
            role_name: e.g. "AE", "SE", "SDR"
            territories_per_seller: 
                - 1.0 means 1:1 (One seller covers exactly one territory)
                - 3.0 means 1:3 (One seller covers three territories)
                - 0.5 means 2:1 (Two sellers cover one territory)
        """
        if territories_per_seller <= 0:
            raise ValueError("Coverage ratio must be > 0")
            
        self.roles[role_name] = {
            'ratio': territories_per_seller
        }
        
    def generate_assignments(self) -> pd.DataFrame:
        """
        Generates the staffing matrix assigning hypothetical reps to territories
        based on the defined rules.
        """
        records = []
        
        for role, config in self.roles.items():
            ratio = config['ratio']
            
            # Case 1: 1:N (e.g., 1 SE for 3 Territories, ratio = 3.0)
            if ratio >= 1.0:
                chunk_size = int(ratio)
                for i in range(0, len(self.territories), chunk_size):
                    chunk = self.territories[i:i + chunk_size]
                    # Create one seller for this chunk
                    seller_id = f"{role}-{str(uuid.uuid4())[:6].upper()}"
                    for t in chunk:
                        records.append({
                            'Territory_ID': t,
                            'Role': role,
                            'Seller_ID': seller_id
                        })
                        
            # Case 2: N:1 (e.g., 2 SDRs for 1 Territory, ratio = 0.5 -> 2 sellers per terr)
            else:
                sellers_per_territory = math.ceil(1.0 / ratio)
                for t in self.territories:
                    for _ in range(sellers_per_territory):
                        seller_id = f"{role}-{str(uuid.uuid4())[:6].upper()}"
                        records.append({
                            'Territory_ID': t,
                            'Role': role,
                            'Seller_ID': seller_id
                        })
                        
        self.assignments = records
        return pd.DataFrame(records)
        
    def get_territory_roster(self) -> pd.DataFrame:
        """
        Pivots the assignments so each row is a territory and columns are roles.
        If a territory has multiple sellers of the same role (N:1), their IDs are comma-separated.
        """
        if not self.assignments:
            self.generate_assignments()
            
        df = pd.DataFrame(self.assignments)
        if df.empty:
            return pd.DataFrame()
            
        # Group by Territory and Role, join multiple sellers with commas
        grouped = df.groupby(['Territory_ID', 'Role'])['Seller_ID'].apply(lambda x: ', '.join(x)).reset_index()
        
        # Pivot table
        pivoted = grouped.pivot(index='Territory_ID', columns='Role', values='Seller_ID').reset_index()
        pivoted = pivoted.fillna('Unassigned')
        
        return pivoted

    def export_to_hierarchy(self, hierarchy_columns_order: List[str] = None) -> pd.DataFrame:
        """
        Exports the staffing roster into a flat hierarchy format designed explicitly
        to be ingested by `b2b_revenue_forecasting.SalesHierarchy`.
        
        Args:
            hierarchy_columns_order: The desired top-down order of roles 
                (e.g., ['Regional_VP', 'Sales_Manager', 'Account_Executive']).
                If None, uses the roles as they were added.
                
        Returns:
            A clean DataFrame ready for `SalesHierarchy.from_dataframe(df, path_cols=...)`
        """
        roster = self.get_territory_roster()
        if roster.empty:
            return roster
            
        # Add a 'Global' root node for the forecasting package
        df = roster.copy()
        df['Global'] = 'Global_Corp'
        
        if hierarchy_columns_order:
            # Validate
            missing = [c for c in hierarchy_columns_order if c not in df.columns]
            if missing:
                raise ValueError(f"Requested roles not found in matrix: {missing}")
            # Ensure Territory is at the leaf level
            cols = ['Global'] + hierarchy_columns_order + ['Territory_ID']
            # Drop unneeded columns
            return df[cols]
            
        return df

if __name__ == "__main__":
    # Example usage
    sample_territories = [
        "AMER_Ent_1", "AMER_Ent_2", "AMER_Ent_3",
        "EMEA_Mid_1", "EMEA_Mid_2"
    ]
    
    matrix = SellerAssignmentMatrix(sample_territories)
    
    # 1 AE per territory (1:1)
    matrix.add_role('Account_Executive', 1.0)
    
    # 1 SE covers 2 territories (1:2)
    matrix.add_role('Sales_Engineer', 2.0)
    
    # 2 BDRs per territory (2:1 or ratio=0.5)
    matrix.add_role('BDR', 0.5)
    
    # Custom Role: 1 VP covers all 5 territories
    matrix.add_role('Regional_VP', 5.0)
    
    roster = matrix.get_territory_roster()
    print("--- Generated Territory Staffing Roster ---")
    print(roster.to_string())
